#!/usr/bin/env python3
"""Generate data/lessons.js — 30 days of original A1.1 content for Deutsch Jetzt!
Narrative: Mia moves to Berlin for a design internship. All content original."""
import json, html

D = []  # days

def day(id, act, title, goal, gtopic, gnote, gex, episode, vocab, chunks, out_prompt, out_model):
    vlist = []
    for i, (de, en, art, typ, ex) in enumerate(vocab, 1):
        vlist.append({"id": f"d{id}_v{i}", "de": de, "en": en, "article": art, "type": typ, "example": ex})
    D.append({
        "id": id, "level": "A1.1", "act": act, "title": title, "goal": goal,
        "grammar": {"topic": gtopic, "note": gnote, "examples": gex},
        "episode": [{"speaker": s, "de": de, "en": en, "audioFile": None} for s, de, en in episode],
        "vocab": vlist,
        "chunks": [{"de": c, "en": e} for c, e in chunks],
        "outputTask": {"prompt": out_prompt, "model": out_model}
    })

# ---------------- TAG 1 ----------------
day(1, "Begrüßung", "Ankunft in Berlin", "Sich begrüßen und vorstellen (Name, Herkunft).",
    "Personalpronomen ich/du/Sie + Verben sein, heißen, kommen (Präsens)",
    "Use <b>ich</b> for yourself, <b>du</b> for friends/young people, <b>Sie</b> (formal) for strangers and work. Verbs end in -e (ich), -st (du), -en (wir/Sie).",
    ["Ich heiße Mia.", "Woher kommst du?", "Ich komme aus Spanien.", "Wie geht es Ihnen?"],
    [("Mia","Hallo! Entschuldigung — wo ist der Bahnhof?","Hi! Excuse me — where is the train station?"),
     ("Jonas","Guten Tag! Der Bahnhof ist hier links. Kommen Sie aus dem Ausland?","Hello! The station is left from here. Are you from abroad?"),
     ("Mia","Ja, ich heiße Mia. Ich komme aus Madrid. Und du?","Yes, I'm Mia. I come from Madrid. And you?"),
     ("Jonas","Ich bin Jonas. Ich wohne in Berlin. Willkommen in Deutschland!","I'm Jonas. I live in Berlin. Welcome to Germany!"),
     ("Mia","Danke! Wie geht es dir?","Thanks! How are you?"),
     ("Jonas","Gut, danke. Und Ihnen? — äh, dir!","Good, thanks. And you? — uh, you (informal)!"),
     ("Mia","Sehr gut. Bis bald!","Very good. See you soon!")],
    [("der Tag","the day","der","noun","Guten Tag!"),
     ("hallo","hello","","interjection","Hallo, wie geht's?"),
     ("heißen","to be called","","verb","Ich heiße Anna."),
     ("kommen","to come","","verb","Ich komme aus Italien."),
     ("wohnen","to live","","verb","Ich wohne in Berlin."),
     ("ich","I","","pronoun","Ich bin neu hier."),
     ("du","you (informal)","","pronoun","Du bist nett."),
     ("Sie","you (formal)","","pronoun","Wie heißen Sie?"),
     ("aus","from (country)","","prep","aus Österreich"),
     ("deutsch","German (lang)","","adj","Ich spreche Deutsch."),
     ("danke","thank you","","interjection","Danke schön!"),
     ("bitte","please / you're welcome","","interjection","Bitte schön!"),
     ("ja","yes","","adverb","Ja, gerne."),
     ("nein","no","","adverb","Nein, danke.")],
    [("Ich heiße …","My name is …"),("Woher kommst du?","Where are you from?"),("Ich komme aus …","I come from …"),("Wie geht es dir?","How are you?"),("Bis bald!","See you soon!")],
    "Introduce yourself out loud: greeting, name, where you are from. Then say goodbye.",
    "Hallo! Ich heiße Mia. Ich komme aus Spanien. Wie geht es dir? — Gut, danke. Auf Wiedersehen!")

# ---------------- TAG 2 ----------------
day(2, "Alphabet & Aussprache", "Das deutsche Alphabet", "Das Alphabet buchstabieren und Umlaute aussprechen.",
    "Alphabet, Umlaute (ä ö ü) und ß; Ausspracheregeln",
    "German has 3 extra vowels: <b>ä</b> (like 'a' in 'cat'), <b>ö</b> (rounded 'e'), <b>ü</b> (rounded 'i'), and <b>ß</b> (sharp s, like 'ss'). 'v' sounds like 'f', 'w' like 'v', 'j' like 'y'.",
    ["Öffne die Tür!", "Die Straße ist lang.", "Ich heiße Jürgen.", "Übung macht den Meister."],
    [("Jonas","Kannst du deinen Namen buchstabieren?","Can you spell your name?"),
     ("Mia","M-I-A. Und mein Nachname: L-Ö-P-E-Z.","M-I-A. And my surname: L-Ö-P-E-Z."),
     ("Jonas","Mit Ö? Interessant! In Deutschland gibt es ä, ö, ü und ß.","With Ö? Interesting! In Germany there are ä, ö, ü and ß."),
     ("Mia","Was ist ß?","What is ß?"),
     ("Jonas","Das ist ein scharfes S, wie in Straße. Es heißt Eszett.","That's a sharp s, like in 'Straße'. It's called Eszett."),
     ("Mia","Ah! Also Straße mit ß. Übung macht den Meister, sagt man?","Ah! So Straße with ß. Practice makes perfect, they say?"),
     ("Jonas","Genau! Sprich langsam, dann klappt es.","Exactly! Speak slowly, then it works.")],
    [("das Alphabet","the alphabet","das","noun","Das deutsche Alphabet hat 26 Buchstaben."),
     ("der Buchstabe","the letter","der","noun","Welcher Buchstabe ist das?"),
     ("buchstabieren","to spell","","verb","Kannst du das buchstabieren?"),
     ("der Umlaut","the umlaut","der","noun","Ä, Ö, Ü sind Umlaute."),
     ("das ß (Eszett)","the sharp s","das","noun","Straße schreibt man mit ß."),
     ("sprechen","to speak","","verb","Ich spreche ein bisschen Deutsch."),
     ("langsam","slowly","","adverb","Sprechen Sie langsam, bitte."),
     ("der Name","the name","der","noun","Mein Name ist Mia."),
     ("der Nachname","the surname","der","noun","Mein Nachname ist López."),
     ("wie","how","","adv","Wie heißt du?"),
     ("was","what","","pronoun","Was ist das?"),
     ("genau","exactly / right","","adv","Ja, genau!"),
     ("klappen","to work out","","verb","Es klappt!")],
    [("Wie buchstabiert man …?","How do you spell …?"),("Können Sie das buchstabieren?","Can you spell that?"),("Sprechen Sie langsam, bitte.","Speak slowly, please."),("Was heißt …?","What does … mean?"),("Wie spricht man das aus?","How do you pronounce that?")],
    "Spell your full name and your city slowly, then write it down from memory.",
    "Mein Name ist Mia López. L-Ö-P-E-Z. Ich komme aus Madrid. M-A-D-R-I-D.")

# ---------------- TAG 3 ----------------
day(3, "Zahlen & Telefon", "Zahlen bis 20 und die Telefonnummer", "Zahlen 1–20 sagen und Telefonnummern austauschen.",
    "Zahlen 0–20; Telefonnummer; wie viel? wie viele?",
    "Numbers 0–12 are irregular (eins, zwei, drei … zwölf). 13–19 = digit + zehn (drei-zehn). Note: <b>null</b>=0, <b>eins</b>=1 but before a noun it's <b>ein</b>. Phone numbers are spoken digit by digit.",
    ["Meine Nummer ist null eins sieben sechs, drei zwei null eins vier.","Ich habe drei Geschwister.","Wie viel kostet das?","Sie ist neunzehn Jahre alt."],
    [("Jonas","Wie ist deine Telefonnummer, Mia?","What's your phone number, Mia?"),
     ("Mia","Null eins fünf eins, vier vier acht null neun drei zwei.","0151, 4480932."),
     ("Jonas","Danke! Ich schreibe sie auf. Wie alt bist du eigentlich?","Thanks! I'll write it down. How old are you, by the way?"),
     ("Mia","Ich bin vierundzwanzig. Und du?","I'm twenty-four. And you?"),
     ("Jonas","Ich bin sechsundzwanzig. Ich habe zwei Schwestern.","I'm twenty-six. I have two sisters."),
     ("Mia","Ich habe einen Bruder und eine Schwester. Wir sind drei Kinder.","I have one brother and one sister. We are three children."),
     ("Jonas","Große Familie! Ich rufe dich später an.","Big family! I'll call you later.")],
    [("null","zero","","number","Die Nummer beginnt mit null."),
     ("eins","one","","number","Ich habe eins."),
     ("zwei","two","","number","zwei Brüder"),
     ("drei","three","","number","drei Kinder"),
     ("zehn","ten","","number","zehn Euro"),
     ("zwanzig","twenty","","number","Er ist zwanzig."),
     ("die Zahl","the number","die","noun","Welche Zahl ist das?"),
     ("die Telefonnummer","the phone number","die","noun","Wie ist deine Telefonnummer?"),
     ("wie alt","how old","","phrase","Wie alt bist du?"),
     ("alt","old","","adj","Ich bin 24 Jahre alt."),
     ("das Jahr","the year","das","noun","in einem Jahr"),
     ("haben","to have","","verb","Ich habe einen Bruder."),
     ("der Bruder","the brother","der","noun","Mein Bruder ist groß."),
     ("die Schwester","the sister","die","noun","zwei Schwestern")],
    [("Wie ist deine Telefonnummer?","What's your phone number?"),("Wie alt bist du?","How old are you?"),("Ich bin … Jahre alt.","I am … years old."),("Ich habe … Geschwister.","I have … siblings."),("Ich rufe dich später an.","I'll call you later.")],
    "Say your phone number, age, and number of siblings in German from memory.",
    "Meine Telefonnummer ist 0151 4480932. Ich bin 24 Jahre alt. Ich habe zwei Geschwister.")

# ---------------- TAG 4 ----------------
day(4, "Länder & Herkunft", "Woher kommst du?", "Über Herkunft, Länder und Nationalitäten sprechen.",
    "Präposition aus + Land; woher?; Nationalitäten (invariabel Adjektiv)",
    "Ask origin with <b>Woher kommst du?</b> Answer with <b>Ich komme aus …</b> (aus + country, no article for most countries). Nationality adjectives have no ending: <b>ich bin spanisch</b>.",
    ["Woher kommst du? — Ich komme aus der Türkei.","Sie ist italienisch.","Wir kommen aus Österreich.","Aus welchem Land kommst du?"] ,
    [("Frau Becker","Guten Tag, Sie müssen Mia sein! Ich bin Frau Becker, Ihre Vermieterin.","Hello, you must be Mia! I'm Mrs. Becker, your landlady."),
     ("Mia","Guten Tag! Ja, ich bin's. Schön, Sie kennenzulernen.","Hello! Yes, that's me. Nice to meet you."),
     ("Frau Becker","Kommen Sie aus Spanien? Ihre Akzent ist spanisch.","Are you from Spain? Your accent is Spanish."),
     ("Mia","Ja, ich komme aus Madrid. Meine Mutter ist kolumbianisch, mein Vater spanisch.","Yes, I'm from Madrid. My mother is Colombian, my father Spanish."),
     ("Frau Becker","Interessant! Mein Mann kommt aus Polen. Wir sprechen zu Hause Polnisch.","Interesting! My husband comes from Poland. We speak Polish at home."),
     ("Mia","Wow, zweisprachig! Ich möchte auch so gut Deutsch sprechen.","Wow, bilingual! I want to speak German that well too."),
     ("Frau Becker","Das schaffen Sie! Hier ist Ihr Schlüssel.","You'll manage! Here is your key.")],
    [("das Land","the country","das","noun","Welches Land ist das?"),
     ("woher","where from","","adv","Woher kommst du?"),
     ("spanisch","Spanish","","adj","Ich bin spanisch."),
     ("deutsch","German","","adj","Er ist deutsch."),
     ("italienisch","Italian","","adj","Sie ist italienisch."),
     ("die Heimat","homeland","die","noun","Meine Heimat ist Madrid."),
     ("der Akzent","the accent","der","noun","Du hast einen spanischen Akzent."),
     ("die Mutter","the mother","die","noun","Meine Mutter kocht gut."),
     ("der Vater","the father","der","noun","Mein Vater arbeitet viel."),
     ("kennenlernen","to meet (get to know)","","verb","Schön, Sie kennenzulernen."),
     ("der Schlüssel","the key","der","noun","Hier ist Ihr Schlüssel."),
     ("die Vermieterin","the landlady","die","noun","Frau Becker ist meine Vermieterin."),
     ("zu Hause","at home","","phrase","Ich bin zu Hause."),
     ("sprechen","to speak","","verb","Wir sprechen Deutsch.")],
    [("Woher kommst du?","Where are you from?"),("Ich komme aus …","I come from …"),("Schön, Sie kennenzulernen.","Nice to meet you."),("Meine Mutter/Vater ist …","My mother/father is …"),("Das schaffen Sie!","You can do it!")],
    "Explain your origin, your parents' origins, and one country you'd like to visit.",
    "Ich komme aus Spanien. Meine Mutter ist kolumbianisch und mein Vater ist spanisch. Ich möchte nach Japan reisen.")

# ---------------- TAG 5 ----------------
day(5, "Sprachen", "Ich spreche ein bisschen Deutsch", "Sagen, welche Sprachen man spricht, und nach Sprachen fragen.",
    "Verbkonjugation Präsens (ich/du/Sie/wir/ihr/sie); sprechen + Sprache",
    "Regular verbs: stem + endings <b>-e, -st, -t, -en, -t, -en</b> (ich mach-e, du mach-st, er mach-t, wir mach-en, ihr mach-t, sie mach-en). <b>sprechen</b> is irregular: ich spreche, du sprichst, er spricht.",
    ["Ich spreche Spanisch und ein bisschen Deutsch.","Sprichst du Englisch?","Wir sprechen zu Hause Polnisch.","Er spricht drei Sprachen."],
    [("Leila","Hallo, du bist Mia, oder? Ich bin Leila, deine Kollegin im Praktikum.","Hi, you're Mia, right? I'm Leila, your internship colleague."),
     ("Mia","Ja, hallo! Sprechen wir Deutsch oder Englisch?","Yes, hi! Shall we speak German or English?"),
     ("Leila","Lass uns Deutsch sprechen! Ich komme aus der Türkei und lerne auch Deutsch.","Let's speak German! I'm from Turkey and also learning German."),
     ("Mia","Super! Ich spreche Spanisch, Englisch und ein bisschen Deutsch.","Great! I speak Spanish, English, and a bit of German."),
     ("Leila","Ich spreche Türkisch, Englisch und Deutsch. Mein Deutsch ist noch nicht perfekt.","I speak Turkish, English, and German. My German isn't perfect yet."),
     ("Mia","Meins auch nicht. Übung macht den Meister!","Mine neither. Practice makes perfect!"),
     ("Leila","Genau. Nach der Arbeit trinken wir einen Kaffee?","Exactly. After work let's have a coffee?")],
    [("die Sprache","the language","die","noun","Welche Sprachen sprichst du?"),
     ("Spanisch","Spanish","","noun","Ich lerne Spanisch."),
     ("Englisch","English","","noun","Sprechen Sie Englisch?"),
     ("Türkisch","Turkish","","noun","Sie spricht Türkisch."),
     ("ein bisschen","a little","","phrase","Ich verstehe ein bisschen."),
     ("verstehen","to understand","","verb","Ich verstehe nicht."),
     ("lernen","to learn","","verb","Ich lerne Deutsch."),
     ("perfekt","perfect","","adj","Dein Deutsch ist perfekt."),
     ("noch","still / yet","","adv","Ich bin noch nicht fertig."),
     ("nicht","not","","adv","Ich verstehe nicht."),
     ("die Kollegin","the (female) colleague","die","noun","Leila ist meine Kollegin."),
     ("das Praktikum","the internship","das","noun","Ich mache ein Praktikum."),
     ("die Arbeit","the work / job","die","noun","Ich gehe zur Arbeit."),
     ("trinken","to drink","","verb","Ich trinke Kaffee.")],
    [("Ich spreche … und ein bisschen …","I speak … and a little …"),("Sprichst du …?","Do you speak …?"),("Ich verstehe (nur) ein bisschen.","I understand (only) a little."),("Lass uns Deutsch sprechen!","Let's speak German!"),("Mein Deutsch ist noch nicht perfekt.","My German isn't perfect yet.")],
    "List all languages you speak, rate them, and say which you're still learning.",
    "Ich spreche Spanisch und Englisch. Ich lerne Deutsch — mein Deutsch ist noch nicht perfekt, aber ich übe jeden Tag.")

# ---------------- TAG 6 ----------------
day(6, "Berufe", "Was bist du von Beruf?", "Nach Berufen fragen und Berufe beschreiben.",
    "Berufe; von Beruf sein; arbeiten bei/in; unregelmäßige Verben (arbeiten, machen)",
    "Ask about jobs: <b>Was bist du von Beruf?</b> or <b>Was machst du beruflich?</b> Say where you work: <b>Ich arbeite bei …</b> (company) / <b>in …</b> (city/field). Many job nouns add -in for female: der Lehrer / die Lehrerin.",
    ["Was bist du von Beruf? — Ich bin Designerin.","Er arbeitet bei Siemens.","Sie ist Ärztin von Beruf.","Ich mache ein Praktikum in Berlin."],
    [("Herr Vogt","Guten Morgen, Mia! Willkommen im Büro. Ich bin Herr Vogt, Ihr Chef.","Good morning, Mia! Welcome to the office. I'm Mr. Vogt, your boss."),
     ("Mia","Guten Morgen, Herr Vogt! Danke, dass ich hier bin.","Good morning, Mr. Vogt! Thank you for having me."),
     ("Herr Vogt","Was machst du beruflich? Du studierst Design, richtig?","What do you do professionally? You study design, right?"),
     ("Mia","Ja, ich bin Designerin. Ich arbeite gerne mit Farben und Typografie.","Yes, I'm a designer. I like working with colors and typography."),
     ("Herr Vogt","Sehr gut. Leila ist Grafikerin, und Tom ist Programmierer.","Very good. Leila is a graphic designer, and Tom is a programmer."),
     ("Mia","Was machen Sie genau, Herr Vogt?","What exactly do you do, Mr. Vogt?"),
     ("Herr Vogt","Ich bin Projektmanager. Ich organisiere die Teams. Fangen wir an!","I'm a project manager. I organize the teams. Let's begin!")],
    [("der Beruf","the profession","der","noun","Was ist dein Beruf?"),
     ("arbeiten","to work","","verb","Ich arbeite in Berlin."),
     ("der Chef / die Chefin","the boss","der","noun","Mein Chef ist nett."),
     ("die Designerin","the (female) designer","die","noun","Sie ist Designerin."),
     ("der Lehrer / die Lehrerin","the teacher","der","noun","Meine Lehrerin heißt Anna."),
     ("der Arzt / die Ärztin","the doctor","der","noun","Er ist Arzt."),
     ("der Student / die Studentin","the student","der","noun","Ich bin Studentin."),
     ("studieren","to study (at university)","","verb","Ich studiere Design."),
     ("machen","to do / make","","verb","Was machst du?"),
     ("das Büro","the office","das","noun","Ich bin im Büro."),
     ("das Team","the team","das","noun","Unser Team ist klein."),
     ("organisieren","to organize","","verb","Ich organisiere die Reise."),
     ("genau","exactly","","adv","Genau das meine ich."),
     ("anfangen","to begin","","verb","Wir fangen um 9 Uhr an.")],
    [("Was bist du von Beruf?","What's your job?"),("Ich arbeite bei/in …","I work at/in …"),("Ich bin … von Beruf.","I am a … by profession."),("Was machst du beruflich?","What do you do for a living?"),("Fangen wir an!","Let's begin!")],
    "State your job/studies, where you work, and describe one colleague's job.",
    "Ich bin Designerin von Beruf. Ich arbeite bei einer Werbeagentur in Berlin. Meine Kollegin Leila ist Grafikerin.")

# ---------------- TAG 7 ----------------
day(7, "Familie", "Meine Familie", "Über Familie sprechen und Possessivartikel verwenden.",
    "haben; Possessivartikel mein/dein/Ihr (Nominativ); Familienmitglieder",
    "Possessive articles (my/your): <b>mein</b> (my, masc/neut), <b>meine</b> (fem/plural); <b>dein/deine</b> (your informal); <b>Ihr/Ihre</b> (your formal). Use <b>haben</b> (habe, hast, hat, haben) to say what you have.",
    ["Mein Bruder ist groß.","Wie viele Geschwister hast du?","Ihre Eltern wohnen in München.","Meine Schwester hat zwei Kinder."],
    [("Leila","Zeig mir mal ein Foto von deiner Familie!","Show me a photo of your family!"),
     ("Mia","Gerne. Das sind meine Eltern, mein Bruder Carlos und meine Schwester Lucia.","Sure. These are my parents, my brother Carlos and my sister Lucia."),
     ("Leila","Wie alt ist dein Bruder?","How old is your brother?"),
     ("Mia","Er ist achtzehn. Meine Schwester ist dreißig und hat zwei Kinder.","He's eighteen. My sister is thirty and has two children."),
     ("Leila","Oh, du bist Tante! Wohnen deine Eltern in Madrid?","Oh, you're an aunt! Do your parents live in Madrid?"),
     ("Mia","Ja, mein Vater ist Koch und meine Mutter ist Lehrerin. Und deine Familie?","Yes, my father is a cook and my mother is a teacher. And your family?"),
     ("Leila","Meine Eltern wohnen in Istanbul. Ich habe eine Schwester in Berlin.","My parents live in Istanbul. I have a sister in Berlin.")],
    [("die Familie","the family","die","noun","Meine Familie ist groß."),
     ("die Eltern","the parents","die","noun","Meine Eltern sind nett."),
     ("mein / meine","my","","poss","Mein Vater ist Koch."),
     ("dein / deine","your (informal)","","poss","Wie heißt dein Bruder?"),
     ("das Kind","the child","das","noun","Sie hat zwei Kinder."),
     ("der Sohn / die Tochter","son / daughter","der","noun","Ihre Tochter ist klein."),
     ("der Onkel / die Tante","uncle / aunt","der","noun","Ich bin Tante."),
     ("die Großeltern","grandparents","die","noun","Meine Großeltern leben in Spanien."),
     ("der Cousin / die Cousine","cousin","der","noun","Mein Cousin wohnt in Berlin."),
     ("das Foto","the photo","das","noun","Zeig mir ein Foto!"),
     ("wohnen","to live","","verb","Ich wohne in Berlin."),
     ("der Koch / die Köchin","cook","der","noun","Mein Vater ist Koch."),
     ("wie viele","how many","","phrase","Wie viele Geschwister hast du?"),
     ("jung","young","","adj","Mein Bruder ist jung.")],
    [("Das sind meine Eltern.","These are my parents."),("Wie alt ist dein/deine …?","How old is your …?"),("Ich habe … Geschwister.","I have … siblings."),("Mein/Meine … ist/sind …","My … is/are …"),("Wohnen deine Eltern in …?","Do your parents live in …?")],
    "Describe your family: parents, siblings, their ages/jobs, where they live.",
    "Meine Eltern wohnen in Madrid. Mein Vater ist Koch und meine Mutter ist Lehrerin. Ich habe einen Bruder und eine Schwester. Meine Schwester hat zwei Kinder.")

# ---------------- TAG 8 ----------------
day(8, "Wohnen & Wohnung", "Die neue Wohnung", "Die Wohnung beschreiben und Möbel benennen.",
    "Präpositionen des Ortes (in, auf, unter, vor, hinter, neben); es gibt",
    "Prepositions of place answer <b>Wo?</b> (where). <b>in</b>=in/inside, <b>auf</b>=on top, <b>unter</b>=under, <b>vor</b>=in front of, <b>hinter</b>=behind, <b>neben</b>=next to. <b>Es gibt</b> = there is/are.",
    ["Das Sofa ist vor dem Fenster.","Es gibt zwei Schlafzimmer.","Die Küche ist neben dem Bad.","Auf dem Tisch steht eine Lampe."],
    [("Frau Becker","Hier ist Ihre Wohnung, Mia. Zwei Zimmer, eine Küche und ein Bad.","Here is your apartment, Mia. Two rooms, a kitchen and a bathroom."),
     ("Mia","Wow, sie ist hell! Wo ist das Bett?","Wow, it's bright! Where is the bed?"),
     ("Frau Becker","Das Bett ist dort hinten, neben dem Schrank. Der Schreibtisch ist vor dem Fenster.","The bed is back there, next to the wardrobe. The desk is in front of the window."),
     ("Mia","Perfekt! Gibt es eine Küche mit Herd?","Perfect! Is there a kitchen with a stove?"),
     ("Frau Becker","Ja, natürlich. Der Kühlschrank steht neben dem Herd. Und die Couch ist im Wohnzimmer.","Yes, of course. The fridge stands next to the stove. And the couch is in the living room."),
     ("Mia","Es gibt sogar einen Balkon! Darf ich auf den Balkon gehen?","There's even a balcony! May I go onto the balcony?"),
     ("Frau Becker","Aber natürlich! Die Aussicht ist schön.","But of course! The view is nice.")],
    [("die Wohnung","the apartment","die","noun","Meine Wohnung ist klein."),
     ("das Zimmer","the room","das","noun","Das Schlafzimmer ist groß."),
     ("die Küche","the kitchen","die","noun","Ich koche in der Küche."),
     ("das Bad","the bathroom","das","noun","Das Bad ist modern."),
     ("das Bett","the bed","das","noun","Das Bett ist bequem."),
     ("der Tisch","the table","der","noun","Auf dem Tisch steht eine Lampe."),
     ("der Schrank","the wardrobe/cupboard","der","noun","Der Schrank ist groß."),
     ("der Balkon","the balcony","der","noun","Ich frühstücke auf dem Balkon."),
     ("in","in / into","","prep","in der Küche"),
     ("auf","on (top of)","","prep","auf dem Tisch"),
     ("unter","under","","prep","unter dem Bett"),
     ("neben","next to","","prep","neben dem Fenster"),
     ("vor","in front of / before","","prep","vor dem Haus"),
     ("es gibt","there is / there are","","phrase","Es gibt einen Supermarkt.")],
    [("Es gibt …","There is/are …"),("Wo ist …? — … ist neben/unter/vor …","Where is …? — It's next to/under/in front of …"),("Darf ich …?","May I …?"),("Die Wohnung ist hell/groß/klein.","The apartment is bright/big/small."),("Hier ist …","Here is …")],
    "Describe your room/home: what furniture there is and where it stands.",
    "In meiner Wohnung gibt es ein Bett, einen Tisch und einen Schrank. Der Schreibtisch ist vor dem Fenster. Die Küche ist neben dem Bad.")

# ---------------- TAG 9 ----------------
day(9, "Hobbys & Freizeit", "Was machst du in deiner Freizeit?", "Über Hobbys sprechen und gern/mögen verwenden.",
    "gern(e) haben; mögen (mag, magst, mag); Verben + gern; Fragen mit was",
    "Express likes with <b>Ich … gern</b> (e.g., ich tanze gern) or <b>Ich mag …</b> (mögen is irregular: ich mag, du magst, er mag). Ask: <b>Was machst du gern?</b> / <b>Was ist dein Hobby?</b>",
    ["Ich lese gern.","Magst du Musik?","Was machst du in deiner Freizeit?","Wir gehen gern ins Kino."],
    [("Jonas","Hast du heute Abend Zeit? Eine Freundin gibt ein Konzert.","Are you free this evening? A friend is giving a concert."),
     ("Mia","Ein Konzert? Ich höre gern Musik! Um wie viel Uhr?","A concert? I like listening to music! What time?"),
     ("Jonas","Um acht. Was machst du sonst so in deiner Freizeit?","At eight. What else do you do in your free time?"),
     ("Mia","Ich lese gern, ich fotografiere gern und ich koche gern. Und du?","I like reading, I like photographing and I like cooking. And you?"),
     ("Jonas","Ich spiele Fußball und ich mag Kino. Ich sehe gern Filme.","I play football and I like cinema. I like watching films."),
     ("Mia","Ich mag auch Kino! Am Wochenende gehen wir zusammen ins Kino?","I also like cinema! At the weekend let's go to the cinema together?"),
     ("Jonas","Super! Ich kenne ein gutes Kino in Kreuzberg.","Great! I know a good cinema in Kreuzberg.")],
    [("die Freizeit","free time","die","noun","Was machst du in deiner Freizeit?"),
     ("das Hobby","the hobby","das","noun","Mein Hobby ist Lesen."),
     ("gern / gerne","gladly / like to","","adv","Ich tanze gern."),
     ("mögen","to like","","verb","Ich mag Kaffee."),
     ("lesen","to read","","verb","Ich lese ein Buch."),
     ("kochen","to cook","","verb","Ich koche gern italienisch."),
     ("spielen","to play","","verb","Er spielt Fußball."),
     ("der Fußball","football/soccer","der","noun","Fußball ist beliebt."),
     ("das Kino","the cinema","das","noun","Wir gehen ins Kino."),
     ("der Film","the film","der","noun","Der Film ist gut."),
     ("die Musik","music","die","noun","Ich höre gern Musik."),
     ("hören","to hear/listen","","verb","Ich höre Radio."),
     ("zusammen","together","","adv","Wir gehen zusammen."),
     ("am Wochenende","at the weekend","","phrase","Am Wochenende schlafe ich lang.")],
    [("Was machst du gern?","What do you like doing?"),("Ich … gern.","I like to …"),("Ich mag …","I like …"),("Hast du heute Abend Zeit?","Are you free this evening?"),("Um wie viel Uhr?","At what time?")],
    "Talk about three hobbies of yours and one you'd like to try.",
    "Ich lese gern und ich fotografiere gern. Ich mag Kino. Ich möchte gern tanzen lernen.")

# ---------------- TAG 10 ----------------
day(10, "Der Arbeitsplatz", "Erster Tag im Büro", "Sich im Büro zurechtfinden und nach Dingen fragen.",
    "Trennbare Verben (anrufen, anfangen, vorstellen); wo? wohin?; im Büro-Vokabular",
    "Separable verbs split: prefix goes to the end. <b>anrufen</b> → <b>Ich rufe dich an.</b> <b>vorstellen</b> → <b>Ich stelle mich vor.</b> <b>anfangen</b> → <b>Wir fangen um 9 an.</b> The prefix is stressed.",
    ["Ich rufe dich später an.","Stell dich mal vor!","Wann fangen wir an?","Er stellt mich seinen Kollegen vor."],
    [("Leila","Guten Morgen! Hier ist dein Schreibtisch. Der Computer ist schon an.","Good morning! Here's your desk. The computer is already on."),
     ("Mia","Danke! Wann fangen wir an?","Thanks! When do we start?"),
     ("Leila","Um neun. Ich stelle dich gleich dem Team vor.","At nine. I'll introduce you to the team right away."),
     ("Mia","Super. Wo ist die Toilette? Und wo kann ich Kaffee holen?","Great. Where is the bathroom? And where can I get coffee?"),
     ("Leila","Die Toilette ist links, die Küche rechts. Ruf mich an, wenn du Hilfe brauchst.","The bathroom is left, the kitchen right. Call me if you need help."),
     ("Mia","Wie ist deine Durchwahl?","What's your extension number?"),
     ("Leila","Die 23. Und hier ist dein Ausweis. Willkommen im Team!","23. And here's your ID badge. Welcome to the team!")],
    [("der Schreibtisch","the desk","der","noun","Mein Schreibtisch ist groß."),
     ("der Computer","the computer","der","noun","Der Computer ist neu."),
     ("anrufen","to call (phone)","","verb","Ich rufe dich an."),
     ("vorstellen","to introduce","","verb","Ich stelle dich vor."),
     ("anfangen","to begin","","verb","Wir fangen um 9 an."),
     ("brauchen","to need","","verb","Ich brauche Hilfe."),
     ("die Hilfe","the help","die","noun","Brauchst du Hilfe?"),
     ("der Ausweis","the ID badge","der","noun","Hier ist dein Ausweis."),
     ("die Toilette","the toilet","die","noun","Wo ist die Toilette?"),
     ("links / rechts","left / right","","adv","Links ist die Küche."),
     ("holen","to get/fetch","","verb","Ich hole Kaffee."),
     ("der Kaffee","coffee","der","noun","Einen Kaffee, bitte."),
     ("gleich","right away / soon","","adv","Ich komme gleich."),
     ("das Team","the team","das","noun","Willkommen im Team!")],
    [("Ich rufe dich an.","I'll call you."),("Ich stelle dich vor.","I'll introduce you."),("Wann fangen wir an?","When do we start?"),("Wo ist …?","Where is …?"),("Brauchst du Hilfe?","Do you need help?")],
    "Describe your first day at work/school: who you met, where things are.",
    "Heute ist mein erster Tag im Büro. Mein Schreibtisch ist neben dem Fenster. Meine Kollegin stellt mich dem Team vor. Ich brauche einen Ausweis und einen Schlüssel.")

# ---------------- TAG 11 ----------------
day(11, "Einkaufen & Lebensmittel", "Einkaufen im Supermarkt", "Lebensmittel einkaufen und nach Preisen fragen.",
    "Akkusativ (den/die/das); einkaufen; wie viel kostet?; Zahlen bis 100",
    "The accusative case marks the direct object. Definite articles change: <b>der→den</b>, <b>die→die</b>, <b>ein→einen</b>. <b>Ich kaufe den Apfel.</b> Ask price: <b>Wie viel kostet das?</b>",
    ["Ich kaufe einen Kaffee und ein Brot.","Wie viel kostet die Milch?","Er liest den Brief.","Wir nehmen den Zug."],
    [("Mia","Entschuldigung, wo finde ich die Milch?","Excuse me, where do I find the milk?"),
     ("Verkäufer","Die Milch ist hinten links, neben dem Käse. Brauchen Sie noch etwas?","The milk is at the back left, next to the cheese. Do you need anything else?"),
     ("Mia","Ja, ich brauche noch Brot, Eier und Obst. Wie viel kostet das Brot?","Yes, I still need bread, eggs and fruit. How much is the bread?"),
     ("Verkäufer","Das Brot kostet drei Euro fünfzig.","The bread costs three euros fifty."),
     ("Mia","Gut, ich nehme es. Und die Äpfel — wie viel kosten sie?","Good, I'll take it. And the apples — how much are they?"),
     ("Verkäufer","Die Äpfel sind zwei Euro das Kilo.","Apples are two euros per kilo."),
     ("Mia","Perfekt. Ich nehme ein Kilo. Zusammen macht das?","Perfect. I'll take a kilo. How much total?"),
     ("Verkäufer","Das macht acht Euro zwanzig. Zahlen Sie bar oder mit Karte?","That's eight euros twenty. Pay cash or card?")],
    [("einkaufen","to shop / buy","","verb","Ich kaufe ein."),
     ("der Supermarkt","the supermarket","der","noun","Ich gehe zum Supermarkt."),
     ("die Milch","the milk","die","noun","Die Milch ist kalt."),
     ("das Brot","the bread","das","noun","Ich kaufe Brot."),
     ("das Ei","the egg","das","noun","Ich brauche Eier."),
     ("der Käse","the cheese","der","noun","Der Käse ist lecker."),
     ("das Obst","the fruit","das","noun","Obst ist gesund."),
     ("der Apfel","the apple","der","noun","Ich esse einen Apfel."),
     ("kosten","to cost","","verb","Was kostet das?"),
     ("der Euro","the euro","der","noun","Es kostet fünf Euro."),
     ("teuer / billig","expensive / cheap","","adj","Das ist teuer!"),
     ("nehmen","to take","","verb","Ich nehme das."),
     ("bezahlen","to pay","","verb","Ich bezahle mit Karte."),
     ("die Karte","the card","die","noun","Zahlen Sie mit Karte?")],
    [("Wie viel kostet …?","How much does … cost?"),("Ich nehme …","I'll take …"),("Brauchen Sie noch etwas?","Do you need anything else?"),("Zahlen Sie bar oder mit Karte?","Pay cash or card?"),("Das macht … Euro.","That's … euros.")],
    "Role-play a supermarket trip: list 5 items you buy and their (invented) prices.",
    "Ich kaufe Milch, Brot, Eier, Käse und Äpfel. Die Milch kostet einen Euro, das Brot drei Euro. Zusammen macht das zehn Euro. Ich bezahle mit Karte.")

# ---------------- TAG 12 ----------------
day(12, "Im Restaurant", "Im italienischen Restaurant", "Im Restaurant bestellen, essen und bezahlen.",
    "Modalverb möchten (möchte, möchtest, möchte); Akkusativ; bestellen",
    "<b>Möchten</b> (would like) is polite for ordering: <b>Ich hätte gern …</b> / <b>Ich möchte …</b>. Conjugation: ich möchte, du möchtest, er/sie möchte, wir möchten, ihr möchtet, sie/Sie möchten. The waiter asks <b>Was möchten Sie?</b>",
    ["Ich hätte gern ein Wasser.","Was möchten Sie essen?","Wir möchten zwei Kaffee, bitte.","Die Rechnung, bitte!"],
    [("Kellner","Guten Abend! Was möchten Sie trinken?","Good evening! What would you like to drink?"),
     ("Mia","Ich hätte gern ein Mineralwasser, bitte. Und ein Bier für meinen Freund.","I'd like a mineral water, please. And a beer for my friend."),
     ("Jonas","Danke! Und wir möchten die Speisekarte sehen.","Thanks! And we'd like to see the menu."),
     ("Kellner","Natürlich. Hier ist die Karte.","Of course. Here's the menu."),
     ("Mia","Ich möchte die Pizza Margherita. Und du?","I'd like the Pizza Margherita. And you?"),
     ("Jonas","Ich nehme die Pasta mit Tomatensauce. Schmeckt dir das?","I'll have the pasta with tomato sauce. Do you like that?"),
     ("Mia","Ja, sehr! Zum Nachtisch möchte ich ein Tiramisu.","Yes, very much! For dessert I'd like a tiramisu."),
     ("Kellner","Und sonst noch etwas? Sonst bringen ich die Rechnung?","Anything else? Otherwise I'll bring the bill?"),
     ("Jonas","Die Rechnung, bitte. Wir zahlen getrennt.","The bill, please. We'll pay separately.")],
    [("das Restaurant","the restaurant","das","noun","Wir gehen ins Restaurant."),
     ("bestellen","to order","","verb","Wir bestellen Pizza."),
     ("möchten","would like","","verb","Ich möchte ein Wasser."),
     ("hätte gern","would like (have)","","phrase","Ich hätte gern ein Bier."),
     ("die Speisekarte","the menu","die","noun","Die Speisekarte, bitte."),
     ("trinken","to drink","","verb","Was trinkst du?"),
     ("essen","to eat","","verb","Ich esse gern Pizza."),
     ("das Bier","the beer","das","noun","Ein Bier, bitte."),
     ("das Wasser","the water","das","noun","Ein Wasser, bitte."),
     ("schmecken","to taste / like (food)","","verb","Schmeckt es dir?"),
     ("der Nachtisch","the dessert","der","noun","Zum Nachtisch nehme ich Eis."),
     ("die Rechnung","the bill","die","noun","Die Rechnung, bitte!"),
     ("bezahlen","to pay","","verb","Wir bezahlen zusammen."),
     ("getrennt / zusammen","separately / together","","adv","Wir zahlen getrennt.")],
    [("Ich hätte gern … / Ich möchte …","I'd like …"),("Was möchten Sie trinken/essen?","What would you like to drink/eat?"),("Die Rechnung, bitte!","The bill, please!"),("Zahlen Sie getrennt oder zusammen?","Separate or together?"),("Schmeckt es dir?","Do you like it (food)?")],
    "Order a full meal (drink, main, dessert) and ask for the bill in German.",
    "Ich hätte gern ein Wasser. Als Hauptgericht möchte ich die Pizza Margherita. Zum Nachtisch nehme ich ein Tiramisu. Die Rechnung, bitte! Wir zahlen zusammen.")

# ---------------- TAG 13 ----------------
day(13, "Essen & Trinken — Präferenzen", "Was isst du gern?", "Essen bevorzugen und verneinen (kein/nicht).",
    "Negation: kein (before nouns) vs nicht (elsewhere); lieber / am liebsten",
    "Use <b>kein</b> to negate a noun with no/indefinite article: <b>Ich trinke keinen Kaffee.</b> Use <b>nicht</b> for verbs/adjectives/specific nouns: <b>Ich trinke Kaffee nicht gern.</b> Preferences: <b>gern</b> (like), <b>lieber</b> (rather), <b>am liebsten</b> (most of all).",
    ["Ich esse keinen Fisch.","Ich trinke nicht gern Milch.","Ich trinke lieber Tee als Kaffee.","Am liebsten esse ich Pizza."],
    [("Leila","Heute Abend machen wir eine Kochabend. Was isst du gern?","Tonight we're doing a cooking evening. What do you like to eat?"),
     ("Mia","Ich esse gern Pasta und Salat. Aber ich esse keinen Fisch.","I like pasta and salad. But I don't eat fish."),
     ("Leila","Kein Problem! Ich koche auch keinen Fisch. Isst du Fleisch?","No problem! I don't cook fish either. Do you eat meat?"),
     ("Mia","Nein, ich bin Vegetarierin. Ich esse kein Fleisch und keine Wurst.","No, I'm vegetarian. I don't eat meat or sausage."),
     ("Leila","Ah, verstehe. Trinkst du Alkohol?","Ah, I see. Do you drink alcohol?"),
     ("Mia","Ja, aber nicht viel. Am liebsten trinke ich Wein. Und du?","Yes, but not much. I like wine most of all. And you?"),
     ("Leila","Ich trinke lieber Bier. Aber heute trinken wir zusammen etwas!","I'd rather drink beer. But today we'll have something together!"),
     ("Mia","Super! Ich bringe einen spanischen Wein mit.","Great! I'll bring a Spanish wine.")],
    [("kein / keine / kein","no (not a/any)","","neg","Ich habe kein Auto."),
     ("nicht","not","","neg","Ich verstehe nicht."),
     ("essen","to eat","","verb","Was isst du gern?"),
     ("der Fisch","the fish","der","noun","Ich esse keinen Fisch."),
     ("das Fleisch","the meat","das","noun","Er isst kein Fleisch."),
     ("der Salat","the salad","der","noun","Ich mache einen Salat."),
     ("die Pasta / die Nudeln","pasta / noodles","die","noun","Die Nudeln schmecken gut."),
     ("vegetarisch","vegetarian","","adj","Ich bin Vegetarierin."),
     ("der Wein","the wine","der","noun","Ein Glas Wein, bitte."),
     ("lieber","rather / prefer","","adv","Ich trinke lieber Tee."),
     ("am liebsten","most of all","","phrase","Am liebsten esse ich Schokolade."),
     ("viel / wenig","much / little","","adj","Ich trinke nicht viel."),
     ("mitbringen","to bring along","","verb","Ich bringe Wein mit."),
     ("kochen","to cook","","verb","Wir kochen zusammen.")],
    [("Ich esse keinen / keine …","I don't eat …"),("Ich bin Vegetarier/in.","I'm vegetarian."),("Ich trinke lieber … als …","I'd rather drink … than …"),("Am liebsten … ich …","What I like most is …"),("Kein Problem!","No problem!")],
    "State your food preferences and allergies, and one thing you'd never eat.",
    "Ich esse gern Pasta und Salat. Ich esse keinen Fisch und kein Fleisch — ich bin Vegetarierin. Ich trinke am liebsten Wein, aber nicht viel.")

# ---------------- TAG 14 ----------------
day(14, "Die Stadt & Wegbeschreibung", "Wie komme ich zum Brandenburger Tor?", "Nach dem Weg fragen und Richtungen angeben.",
    "Präpositionen mit Akkusativ (Richtung: in, auf, an, zu); Wohin? vs Wo?",
    "Ask direction with <b>Wohin?</b> (where to) and location with <b>Wo?</b> (where at). Prepositions of direction take accusative: <b>in den Park</b>, <b>auf die Straße</b>, <b>zum Bahnhof</b> (zu + dem = zum). Give directions: geradeaus, links/rechts abbiegen.",
    ["Wie komme ich zum Bahnhof?","Gehen Sie geradeaus, dann links.","Ich gehe in den Park.","Wir fahren zur Oper."],
    [("Mia","Entschuldigung, wie komme ich zum Brandenburger Tor?","Excuse me, how do I get to the Brandenburg Gate?"),
     ("Passant","Gehen Sie hier geradeaus, dann an der zweiten Kreuzung links abbiegen.","Go straight here, then turn left at the second intersection."),
     ("Mia","Und dann?","And then?"),
     ("Passant","Dann gehen Sie die Straße entlang, bis zum Park. Das Tor ist rechts vom Park.","Then go along the street, up to the park. The gate is to the right of the park."),
     ("Mia","Ist es weit? Soll ich die U-Bahn nehmen?","Is it far? Should I take the subway?"),
     ("Passant","Nein, es sind nur zehn Minuten zu Fuß. Viel Spaß in Berlin!","No, it's only ten minutes on foot. Enjoy Berlin!"),
     ("Mia","Danke! Sie sind sehr hilfsbereit.","Thanks! You're very helpful.")],
    [("der Weg","the way / path","der","noun","Welcher Weg ist richtig?"),
     ("geradeaus","straight ahead","","adv","Gehen Sie geradeaus."),
     ("links / rechts abbiegen","to turn left/right","","verb","Biegen Sie links ab."),
     ("die Kreuzung","the intersection","die","noun","An der Kreuzung rechts."),
     ("bis zum","up to the","","prep","Bis zum Ende der Straße."),
     ("entlang","along","","prep","die Straße entlang"),
     ("weit","far","","adj","Ist es weit?"),
     ("zu Fuß","on foot","","phrase","Ich gehe zu Fuß."),
     ("die U-Bahn","the subway","die","noun","Ich nehme die U-Bahn."),
     ("nehmen","to take","","verb","Ich nehme den Bus."),
     ("der Park","the park","der","noun","Wir gehen in den Park."),
     ("das Tor","the gate","das","noun","Das Brandenburger Tor."),
     ("hilfsbereit","helpful","","adj","Sie sind hilfsbereit."),
     ("sich befinden","to be located","","verb","Wo befindet sich das Kino?")],
    [("Wie komme ich zum/zur …?","How do I get to …?"),("Gehen Sie geradeaus / links / rechts.","Go straight / left / right."),("An der Kreuzung … abbiegen.","Turn … at the intersection."),("Es sind … Minuten zu Fuß.","It's … minutes on foot."),("Soll ich die U-Bahn nehmen?","Should I take the subway?")],
    "Give directions from your home to a nearby landmark, in German.",
    "Gehen Sie von meiner Wohnung geradeaus, dann an der ersten Kreuzung rechts. Dann bis zum Park, das Kino ist links vom Park. Es sind fünf Minuten zu Fuß.")

# ---------------- TAG 15 ----------------
day(15, "Im Hotel", "Eine Nacht im Hotel", "Im Hotel ankommen, ein Zimmer buchen und Probleme melden.",
    "möchten + Buchung; es gibt; Präpositionen im Zimmer; haben + Problem",
    "Hotel phrases use formal <b>Sie</b>. <b>Ich habe ein Zimmer reserviert.</b> Complain: <b>Es gibt kein …</b> / <b>Das … funktioniert nicht.</b> Key words: das Zimmer, die Rezeption, der Schlüssel, das Bad, der Schlüssel.",
    ["Ich habe ein Zimmer reserviert.","Haben Sie ein freies Zimmer?","Das WLAN funktioniert nicht.","Um wie viel Uhr ist das Frühstück?"],
    [("Rezeption","Guten Abend! Willkommen im Hotel. Haben Sie reserviert?","Good evening! Welcome to the hotel. Do you have a reservation?"),
     ("Mia","Ja, ich habe ein Einzelzimmer auf den Namen López reserviert.","Yes, I reserved a single room under the name López."),
     ("Rezeption","Bitte sehr. Hier ist Ihr Schlüssel, Zimmer 204. Das Frühstück ist von sieben bis zehn.","Here you go. Here's your key, room 204. Breakfast is from seven to ten."),
     ("Mia","Danke. Gibt es WLAN im Zimmer?","Thanks. Is there wifi in the room?"),
     ("Rezeption","Ja, das Passwort steht auf dem Tisch.","Yes, the password is on the table."),
     ("Mia","(später) Entschuldigung, das Licht im Bad funktioniert nicht.","(later) Excuse me, the light in the bathroom doesn't work."),
     ("Rezeption","Oh, Entschuldigung! Ein Techniker kommt sofort. Wir bringen Ihnen eine neue Lampe.","Oh, sorry! A technician comes immediately. We'll bring you a new lamp."),
     ("Mia","Danke. Und wo ist der Aufzug?","Thanks. And where is the elevator?")],
    [("das Hotel","the hotel","das","noun","Wir schlafen im Hotel."),
     ("das Zimmer","the room","das","noun","Das Zimmer ist ruhig."),
     ("reservieren","to reserve","","verb","Ich habe reserviert."),
     ("die Rezeption","the reception","die","noun","Ich gehe zur Rezeption."),
     ("der Schlüssel","the key","der","noun","Hier ist Ihr Schlüssel."),
     ("das Frühstück","the breakfast","das","noun","Das Frühstück ist inklusive."),
     ("das WLAN","the wifi","das","noun","Das WLAN ist schnell."),
     ("das Passwort","the password","das","noun","Wie ist das Passwort?"),
     ("funktionieren","to work/function","","verb","Das Licht funktioniert nicht."),
     ("der Aufzug","the elevator","der","noun","Wo ist der Aufzug?"),
     ("das Einzelzimmer","single room","das","noun","Ich habe ein Einzelzimmer."),
     ("das Doppelzimmer","double room","das","noun","Wir möchten ein Doppelzimmer."),
     ("inklusive","included","","adj","Frühstück ist inklusive."),
     ("ruhig","quiet","","adj","Das Zimmer ist ruhig.")],
    [("Ich habe ein Zimmer reserviert.","I have reserved a room."),("Haben Sie ein freies Zimmer?","Do you have a free room?"),("Um wie viel Uhr ist das Frühstück?","What time is breakfast?"),("Das … funktioniert nicht.","The … doesn't work."),("Wie ist das Passwort?","What's the password?")],
    "Check into a hotel: give your name, ask about breakfast and wifi, report one problem.",
    "Guten Abend! Ich habe ein Einzelzimmer reserviert, auf den Namen López. Um wie viel Uhr ist das Frühstück? Leider funktioniert das Licht im Bad nicht.")

# ---------------- TAG 16 ----------------
day(16, "Verkehrsmittel", "Mit der Bahn nach Hamburg", "Verkehrsmittel benutzen und Fahrkarten kaufen.",
    "fahren (fährst, fährt); mit + Dativ (fixed: mit dem Zug); von … nach …",
    "Travel: <b>Ich fahre mit dem Zug/der Bahn/dem Bus/dem Fahrrad.</b> (mit + dative is a fixed pattern — learn it as a chunk). Routes: <b>von Berlin nach Hamburg</b>. <b>fahren</b> is irregular: ich fahre, du fährst, er fährt.",
    ["Ich fahre mit dem Zug nach Hamburg.","Der Zug fährt um 9 Uhr ab.","Von hier bis zum Bahnhof sind es 10 Minuten.","Mit welcher Bahn fahre ich?"] ,
    [("Mia","Am Wochenende fahre ich nach Hamburg. Hast du Lust mitzukommen?","At the weekend I'm going to Hamburg. Do you want to come along?"),
     ("Jonas","Klar! Wie fahren wir hin? Mit dem Auto?","Sure! How do we get there? By car?"),
     ("Mia","Nein, ich fahre lieber mit dem Zug. Es ist entspannter.","No, I'd rather go by train. It's more relaxing."),
     ("Jonas","Gut. Wann fährt der Zug ab? Und wo steigen wir ein?","Good. When does the train leave? And where do we board?"),
     ("Mia","Der Zug fährt um acht Uhr dreißig vom Hauptbahnhof ab, Gleis fünf.","The train leaves at 8:30 from the main station, track five."),
     ("Jonas","Und die Rückfahrt? Wann kommen wir zurück?","And the return? When do we come back?"),
     ("Mia","Sonntag Abend, um sieben Uhr. Ich kaufe die Fahrkarten online.","Sunday evening, at seven. I'll buy the tickets online."),
     ("Jonas","Super! Ich bringe Snacks mit.","Great! I'll bring snacks.")],
    [("das Verkehrsmittel","means of transport","das","noun","Welches Verkehrsmittel nimmst du?"),
     ("der Zug / die Bahn","the train","der","noun","Der Zug ist pünktlich."),
     ("fahren","to drive/travel","","verb","Ich fahre nach Hamburg."),
     ("abfahren","to depart","","verb","Der Zug fährt um 8 ab."),
     ("einsteigen","to board/get in","","verb","Wir steigen in Berlin ein."),
     ("aussteigen","to get off","","verb","Wo steigen wir aus?"),
     ("der Hauptbahnhof","main station","der","noun","Ich treffe dich am Hauptbahnhof."),
     ("das Gleis","the platform/track","das","noun","Der Zug fährt von Gleis 5 ab."),
     ("die Fahrkarte","the ticket","die","noun","Ich kaufe eine Fahrkarte."),
     ("von … nach …","from … to …","","prep","von Berlin nach Hamburg"),
     ("zurück","back","","adv","Wann kommst du zurück?"),
     ("die Rückfahrt","the return trip","die","noun","Die Rückfahrt ist um 19 Uhr."),
     ("pünktlich","on time","","adj","Die Bahn ist pünktlich."),
     ("mitkommen","to come along","","verb","Kommst du mit?")],
    [("Ich fahre mit dem Zug/Bus/Auto.","I travel by train/bus/car."),("Wann fährt der Zug ab?","When does the train leave?"),("Von welchem Gleis?","From which platform?"),("Wo steige ich um/aus?","Where do I change/get off?"),("Hast du Lust mitzukommen?","Do you want to come along?")],
    "Plan a trip: destination, transport, departure time and platform, return time.",
    "Am Wochenende fahre ich mit dem Zug nach Hamburg. Der Zug fährt um 8:30 vom Hauptbahnhof, Gleis 5, ab. Die Rückfahrt ist Sonntag um 19 Uhr.")

# ---------------- TAG 17 ----------------
day(17, "Tagesablauf & Uhrzeit", "Ein normaler Tag", "Den Tagesablauf beschreiben und die Uhrzeit sagen.",
    "Uhrzeit (offiziell vs informell); trennbare Verben des Alltags (aufstehen, frühstücken, losgehen)",
    "Tell time: official <b>Es ist 14 Uhr 30</b>; informal <b>Es ist halb drei</b> (half past two!). Routine verbs: <b>aufstehen</b> (stehe auf), <b>frühstücken</b>, <b>losgehen</b> (gehe los), <b>nach Hause kommen</b>.",
    ["Ich stehe um sieben Uhr auf.","Es ist halb vier (15:30).","Der Unterricht beginnt um neun Uhr.","Ich komme um sechs nach Hause."],
    [("Leila","Wie sieht dein normaler Tag aus, Mia? Wann stehst du auf?","What does your normal day look like, Mia? When do you get up?"),
     ("Mia","Ich stehe um sieben Uhr auf. Dann dusche ich und frühstücke ich um halb acht.","I get up at seven. Then I shower and have breakfast at half past seven."),
     ("Leila","Wann gehst du zur Arbeit?","When do you go to work?"),
     ("Mia","Ich gehe um acht Uhr los. Die Arbeit beginnt um neun.","I leave at eight. Work starts at nine."),
     ("Leila","Und wann ist Feierabend?","And when do you finish work?"),
     ("Mia","Um fünf Uhr nachmittags. Dann gehe ich manchmal ins Fitnessstudio.","At five in the afternoon. Then I sometimes go to the gym."),
     ("Leila","Wann isst du zu Abend?","When do you have dinner?"),
     ("Mia","Um halb acht. Um elf Uhr gehe ich schlafen. Und du?","At half past seven. At eleven I go to sleep. And you?"),
     ("Leila","Ich bin eine Nachteule — ich schlafe erst um Mitternacht.","I'm a night owl — I only sleep at midnight.")],
    [("aufstehen","to get up","","verb","Ich stehe um 7 auf."),
     ("frühstücken","to have breakfast","","verb","Wir frühstücken um 8."),
     ("losgehen","to leave/set off","","verb","Ich gehe um 8 los."),
     ("der Tag","the day","der","noun","Ein normaler Tag."),
     ("die Uhr","clock / o'clock","die","noun","Wie viel Uhr ist es?"),
     ("halb acht","half past seven (7:30)","","phrase","Es ist halb acht."),
     ("viertel nach","quarter past","","phrase","Es ist viertel nach drei."),
     ("die Arbeit beginnt","work starts","","phrase","Die Arbeit beginnt um 9."),
     ("der Feierabend","end of work","der","noun","Wann ist Feierabend?"),
     ("nach Hause kommen","to come home","","phrase","Ich komme um 6 nach Hause."),
     ("zu Abend essen","to have dinner","","phrase","Wir essen um 7 zu Abend."),
     ("schlafen gehen","to go to sleep","","phrase","Ich gehe um 11 schlafen."),
     ("manchmal","sometimes","","adv","Ich gehe manchmal ins Kino."),
     ("die Nachteule","night owl","die","noun","Er ist eine Nachteule.")],
    [("Wann stehst du auf?","When do you get up?"),("Ich stehe um … Uhr auf.","I get up at …"),("Es ist … Uhr / halb …","It's … o'clock / half past …"),("Wann ist Feierabend?","When do you finish work?"),("Ich gehe um … schlafen.","I go to sleep at …")],
    "Describe your typical day from waking up to going to sleep, with times.",
    "Ich stehe um sieben Uhr auf. Ich frühstücke um halb acht. Die Arbeit beginnt um neun. Um fünf ist Feierabend. Ich esse um halb acht zu Abend und gehe um elf schlafen.")

# ---------------- TAG 18 ----------------
day(18, "Termine vereinbaren", "Hast du am Mittwoch Zeit?", "Einen Termin vereinbaren und absagen.",
    "Wochentage; Uhrzeit für Termine; haben + Zeit; Präpositionen der Zeit (am, um, von…bis)",
    "Days: Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag/Sonnabend, Sonntag. Use <b>am</b> + day (am Mittwoch), <b>um</b> + time (um 15 Uhr), <b>von … bis …</b> (from…to). Agree: <b>Das passt.</b> Decline: <b>Da habe ich leider keine Zeit.</b>",
    ["Hast du am Mittwoch Zeit?","Treffen wir uns um 15 Uhr.","Ich habe von 9 bis 17 Uhr Arbeit.","Leider kann ich nicht.","Das passt!"] ,
    [("Herr Vogt","Mia, können wir kurz einen Termin besprechen? Nächste Woche ist ein wichtiges Meeting.","Mia, can we briefly discuss an appointment? Next week there's an important meeting."),
     ("Mia","Natürlich. An welchem Tag?","Of course. Which day?"),
     ("Herr Vogt","Am Mittwoch oder Donnerstag. Passt dir Mittwoch um 10 Uhr?","Wednesday or Thursday. Does Wednesday at 10am suit you?"),
     ("Mia","Am Mittwoch habe ich von 9 bis 12 Uhr einen Termin beim Bürgeramt. Geht es um 14 Uhr?","On Wednesday I have an appointment at the citizens' office from 9 to 12. Would 2pm work?"),
     ("Herr Vogt","Um 14 Uhr habe ich leider keine Zeit. Donnerstag um 11 Uhr?","At 2pm I unfortunately have no time. Thursday at 11am?"),
     ("Mia","Donnerstag um 11 Uhr passt perfekt. Wo treffen wir uns?","Thursday at 11am fits perfectly. Where do we meet?"),
     ("Herr Vogt","Im Konferenzraum, Raum 3. Ich schicke dir eine Einladung per E-Mail.","In the conference room, room 3. I'll send you an invitation by email."),
     ("Mia","Super, danke! Ich schreibe es mir in den Kalender.","Great, thanks! I'll write it in my calendar.")],
    [("der Termin","the appointment","der","noun","Ich habe einen Termin."),
     ("vereinbaren","to arrange","","verb","Wir vereinbaren einen Termin."),
     ("Montag bis Sonntag","Monday to Sunday","","noun","Am Montag habe ich frei."),
     ("am Wochentag","on (day)","","prep","am Mittwoch"),
     ("um … Uhr","at … o'clock","","prep","um 14 Uhr"),
     ("von … bis …","from … to …","","prep","von 9 bis 17 Uhr"),
     ("Zeit haben","to have time","","phrase","Hast du Zeit?"),
     ("passt (mir)","(it) suits (me)","","verb","Das passt mir."),
     ("leider","unfortunately","","adv","Leider kann ich nicht."),
     ("absagen","to cancel","","verb","Ich muss den Termin absagen."),
     ("treffen","to meet","","verb","Wir treffen uns um 3."),
     ("das Meeting","the meeting","das","noun","Das Meeting ist wichtig."),
     ("der Konferenzraum","conference room","der","noun","Im Konferenzraum, Raum 3."),
     ("die E-Mail","the email","die","noun","Ich schicke eine E-Mail.")],
    [("Hast du am … Zeit?","Are you free on …?"),("Passt dir … um … Uhr?","Does … at … suit you?"),("Das passt (perfekt)!","That suits (me perfectly)!"),("Leider habe ich da keine Zeit.","Unfortunately I have no time then."),("Wo treffen wir uns?","Where do we meet?")],
    "Negotiate an appointment: propose two days/times, decline one, agree on one.",
    "Hast du am Mittwoch um 10 Uhr Zeit? — Leider nein, ich habe dann einen Termin. Geht es am Donnerstag um 11 Uhr? — Ja, das passt perfekt!")

# ---------------- TAG 19 ----------------
day(19, "Wetter & Jahreszeiten", "Heute regnet es!", "Über das Wetter und die Jahreszeiten sprechen.",
    "es ist / es gibt Wetter; Adjektive (kalt, warm, sonnig, regnerisch); Jahreszeiten",
    "Weather uses <b>es</b>: <b>Es regnet.</b> (it rains), <b>Es ist kalt/warm/sonnig.</b>, <b>Es gibt Schnee.</b> Seasons: der Frühling, der Sommer, der Herbst, der Winter. In + season: <b>im Sommer</b> (in + dem = im).",
    ["Heute regnet es.","Im Sommer ist es warm.","Wie ist das Wetter?","Es schneit im Winter."],
    [("Jonas","Zieh dich warm an! Heute regnet es und es ist nur acht Grad.","Dress warm! Today it's raining and it's only eight degrees."),
     ("Mia","Acht Grad? Im September? In Madrid ist es noch warm!","Eight degrees? In September? In Madrid it's still warm!"),
     ("Jonas","Ja, in Deutschland ist der Herbst oft kalt und nass. Magst du Regen?","Yes, in Germany autumn is often cold and wet. Do you like rain?"),
     ("Mia","Nicht so gern. Ich liebe Sonne und Wärme. Ich mag den Sommer am liebsten.","Not really. I love sun and warmth. I like summer most of all."),
     ("Jonas","Ich mag den Frühling. Dann blühen die Bäume und es wird langsam warm.","I like spring. Then the trees bloom and it slowly gets warm."),
     ("Mia","Und Winter? Schnee mag ich! Ich möchte mal Schnee sehen.","And winter? I like snow! I'd like to see snow sometime."),
     ("Jonas","Im Dezember schneit es oft. Dann gehen wir Schlittschuhlaufen!","In December it often snows. Then we'll go ice skating!"),
     ("Mia","Das klingt gut! Aber jetzt hole ich erst mal meinen Regenschirm.","That sounds good! But first I'll get my umbrella.")],
    [("das Wetter","the weather","das","noun","Wie ist das Wetter?"),
     ("regnen","to rain","","verb","Es regnet."),
     ("schneien","to snow","","verb","Im Winter schneit es."),
     ("sonnig","sunny","","adj","Heute ist es sonnig."),
     ("kalt / warm","cold / warm","","adj","Es ist kalt."),
     ("der Frühling","spring","der","noun","Im Frühling blühen die Blumen."),
     ("der Sommer","summer","der","noun","Der Sommer ist heiß."),
     ("der Herbst","autumn","der","noun","Der Herbst ist nass."),
     ("der Winter","winter","der","noun","Im Winter schneit es."),
     ("der Regen","the rain","der","noun","Ich mag keinen Regen."),
     ("der Regenschirm","the umbrella","der","noun","Ich hole meinen Regenschirm."),
     ("die Temperatur","the temperature","die","noun","Die Temperatur ist 8 Grad."),
     ("Grad","degrees","","noun","Es hat 25 Grad."),
     ("klingen","to sound","","verb","Das klingt gut!")],
    [("Wie ist das Wetter heute?","How's the weather today?"),("Es regnet/schneit/scheint die Sonne.","It's raining/snowing/sunny."),("Im … ist es …","In … it is …"),("Ich mag den … am liebsten.","I like … most of all."),("Zieh dich warm an!","Dress warm!")],
    "Describe today's weather, your favorite season, and why.",
    "Heute regnet es und es ist kalt, nur 8 Grad. Ich mag den Sommer am liebsten, weil es warm ist und die Sonne scheint. Im Winter schneit es oft in Berlin.")

# ---------------- TAG 20 ----------------
day(20, "Am Computer & Internet", "Ich schicke dir eine E-Mail", "Über Computer und Internet sprechen, digital kommunizieren.",
    "Trennbare Verben (anmelden, ausschalten, herunterladen); Computer-Vokabular; senden/schicken",
    "Digital separable verbs: <b>anmelden</b> → ich melde mich an (log in), <b>ausschalten</b> → schalte aus, <b>herunterladen</b> → lade herunter. Communication: <b>Ich schicke/sende dir eine E-Mail/Nachricht.</b>",
    ["Ich schicke dir eine E-Mail.","Ich melde mich später an.","Laden Sie die Datei herunter.","Schalten Sie den Computer aus."],
    [("Tom","Hi Mia, ich bin Tom, der Programmierer. Brauchst du Hilfe mit dem Computer?","Hi Mia, I'm Tom, the programmer. Do you need help with the computer?"),
     ("Mia","Ja, danke! Ich kann mich nicht anmelden. Das Passwort funktioniert nicht.","Yes, thanks! I can't log in. The password doesn't work."),
     ("Tom","Kein Problem. Ich setze das Passwort zurück. Dann schicke ich dir eine E-Mail.","No problem. I'll reset the password. Then I'll send you an email."),
     ("Mia","Super! Und wie verbinde ich mich mit dem WLAN?","Great! And how do I connect to the wifi?"),
     ("Tom","Wähle das Netzwerk 'Office-Gast' aus. Das Passwort steht auf dem Zettel.","Select the network 'Office-Guest'. The password is on the note."),
     ("Mia","Danke! Kann ich Dateien auf den Server herunterladen?","Thanks! Can I download files onto the server?"),
     ("Tom","Ja, aber speichere alles im Ordner 'Projekte'. Am Ende schaltest du den Computer aus.","Yes, but save everything in the 'Projects' folder. At the end turn off the computer."),
     ("Mia","Alles klar! Du bist eine große Hilfe.","Got it! You're a big help.")],
    [("der Computer","the computer","der","noun","Der Computer ist neu."),
     ("sich anmelden","to log in","","verb","Ich melde mich an."),
     ("ausschalten","to turn off","","verb","Schalte den Computer aus."),
     ("herunterladen","to download","","verb","Ich lade die Datei herunter."),
     ("die E-Mail schicken","to send an email","","phrase","Ich schicke dir eine E-Mail."),
     ("das Passwort","the password","das","noun","Ich habe mein Passwort vergessen."),
     ("das WLAN / Netzwerk","wifi / network","das","noun","Verbinde dich mit dem WLAN."),
     ("die Datei","the file","die","noun","Die Datei ist groß."),
     ("der Ordner","the folder","der","noun","Speichere es im Ordner."),
     ("speichern","to save","","verb","Speichere das Dokument!"),
     ("zurücksetzen","to reset","","verb","Ich setze das Passwort zurück."),
     ("senden / schicken","to send","","verb","Ich sende dir eine Nachricht."),
     ("die Nachricht","the message","die","noun","Ich habe eine Nachricht bekommen."),
     ("helfen","to help","","verb","Kannst du mir helfen?")],
    [("Ich schicke/sende dir eine E-Mail.","I'll send you an email."),("Ich kann mich nicht anmelden.","I can't log in."),("Wie verbinde ich mich mit dem WLAN?","How do I connect to wifi?"),("Speichern Sie die Datei.","Save the file."),("Schalten Sie den Computer aus.","Turn off the computer.")],
    "Explain a small tech problem and how someone helped you fix it.",
    "Ich kann mich nicht am Computer anmelden — das Passwort funktioniert nicht. Tom setzt das Passwort zurück und schickt mir eine E-Mail. Dann verbinde ich mich mit dem WLAN.")

# ---------------- TAG 21 ----------------
day(21, "Stress & Entschuldigungen", "Ich komme zu spät!", "Sich entschuldigen und Verspätung erklären.",
    "müssen (muss, musst, muss); weil (Ursache, Nebensatz — Verb am Ende); Entschuldigung",
    "<b>müssen</b> (must/have to): ich muss, du musst, er muss. <b>weil</b> (because) starts a subordinate clause — the verb goes to the end: <b>Ich komme zu spät, weil der Zug Verspätung hat.</b> Apologize: <b>Entschuldigung!</b> / <b>Es tut mir leid!</b>",
    ["Es tut mir leid, ich komme zu spät.","Ich muss arbeiten.","Ich bleibe zu Hause, weil ich krank bin.","Entschuldigung, dass ich zu spät komme!"] ,
    [("Mia","(im Büro, atmet schwer) Entschuldigung! Es tut mir leid, dass ich zu spät komme!","(in the office, breathing hard) Sorry! I'm sorry I'm late!"),
     ("Herr Vogt","Kein Problem. Ist alles in Ordnung?","No problem. Is everything okay?"),
     ("Mia","Ja, aber die U-Bahn hatte Verspätung. Ich musste warten.","Yes, but the subway was delayed. I had to wait."),
     ("Herr Vogt","Das passiert. In Berlin muss man immer etwas Zeit einplanen.","That happens. In Berlin you always have to plan in some time."),
     ("Mia","Stimmt. Morgen muss ich früher losgehen.","Right. Tomorrow I have to leave earlier."),
     ("Herr Vogt","Kein Stress. Aber du musst die Präsentation heute noch fertig machen.","No stress. But you have to finish the presentation today."),
     ("Mia","Kein Problem, ich mache sie in der Mittagspause fertig.","No problem, I'll finish it during the lunch break."),
     ("Herr Vogt","Gut. Und entschuldigen Sie sich bitte bei dem Kunden — er wartet schon.","Good. And please apologize to the client — he's already waiting.")],
    [("sich entschuldigen","to apologize","","verb","Ich entschuldige mich."),
     ("zu spät","too late","","phrase","Ich komme zu spät."),
     ("Es tut mir leid!","I'm sorry!","","phrase","Es tut mir leid!"),
     ("müssen","to have to / must","","verb","Ich muss gehen."),
     ("weil","because","","conj","Ich bleibe zu Hause, weil ich krank bin."),
     ("die Verspätung","the delay","die","noun","Der Zug hat Verspätung."),
     ("passieren","to happen","","verb","Das passiert."),
     ("früher","earlier","","adv","Ich muss früher losgehen."),
     ("der Stress","the stress","der","noun","Kein Stress!"),
     ("fertig machen","to finish","","verb","Ich mache die Präsentation fertig."),
     ("die Präsentation","the presentation","die","noun","Die Präsentation ist gut."),
     ("die Mittagspause","lunch break","die","noun","In der Mittagspause esse ich."),
     ("warten","to wait","","verb","Ich muss warten."),
     ("der Kunde","the customer/client","der","noun","Der Kunde wartet.")],
    [("Entschuldigung! / Es tut mir leid!","Sorry! / I'm sorry!"),("Ich komme zu spät, weil …","I'm late because …"),("Ich muss …","I have to …"),("Das passiert.","That happens."),("Kein Problem / kein Stress.","No problem / no stress.")],
    "Apologize for being late, give a reason with 'weil', and promise to do better.",
    "Entschuldigung, ich komme zu spät! Ich musste warten, weil die U-Bahn Verspätung hatte. Morgen gehe ich früher los. Es tut mir leid!")

# ---------------- TAG 22 ----------------
day(22, "Gesundheit & Arzt", "Ich habe Kopfschmerzen", "Über Beschwerden sprechen und zum Arzt gehen.",
    "Ich habe … (Schmerzen); weh tun; müssen; Körperteile; Rat geben",
    "Describe ailments with <b>Ich habe Kopfschmerzen/Halsschmerzen/Fieber.</b> or <b>Mir tut der Kopf weh.</b> (weh tun: es tut mir weh). Advice: <b>Du solltest …</b> (you should — sollen). <b>Gehen Sie zum Arzt!</b>",
    ["Ich habe Kopfschmerzen.","Mir tut der Bauch weh.","Du solltest zum Arzt gehen.","Ich habe Fieber."],
    [("Leila","Du siehst blass aus, Mia. Ist alles in Ordnung?","You look pale, Mia. Is everything okay?"),
     ("Mia","Mir ist schlecht. Ich habe Kopfschmerzen und Halsschmerzen.","I feel sick. I have a headache and a sore throat."),
     ("Leila","Hast du Fieber?","Do you have a fever?"),
     ("Mia","Ich glaube schon. Mir tut auch der Hals weh, wenn ich schlucke.","I think so. My throat also hurts when I swallow."),
     ("Leila","Du solltest nach Hause gehen und dich ausruhen. Trink viel Tee!","You should go home and rest. Drink lots of tea!"),
     ("Mia","Du hast recht. Ich rufe beim Arzt an und morgen gehe ich hin.","You're right. I'll call the doctor and tomorrow I'll go."),
     ("Leila","Gute Idee. Ich schreibe dich krank. Melde dich, wenn es dir besser geht!","Good idea. I'll report you sick. Get in touch when you feel better!"),
     ("Mia","Danke, du bist die Beste!","Thanks, you're the best!")],
    [("gesund","healthy","","adj","Ich bin gesund."),
     ("der Schmerz","the pain","der","noun","Ich habe Schmerzen."),
     ("Kopfschmerzen haben","to have a headache","","phrase","Ich habe Kopfschmerzen."),
     ("Fieber haben","to have a fever","","phrase","Das Kind hat Fieber."),
     ("weh tun","to hurt","","verb","Mir tut der Kopf weh."),
     ("der Hals","the throat","der","noun","Ich habe Halsschmerzen."),
     ("der Arzt / die Ärztin","the doctor","der","noun","Ich gehe zum Arzt."),
     ("sich ausruhen","to rest","","verb","Ruhe dich aus!"),
     ("sollen","should / ought to","","verb","Du solltest Tee trinken."),
     ("trinken","to drink","","verb","Trink viel Wasser!"),
     ("der Tee","the tea","der","noun","Eine Tasse Tee, bitte."),
     ("krank","sick","","adj","Ich bin krank."),
     ("krank schreiben","to report sick (doctor's note)","","phrase","Der Arzt schreibt mich krank."),
     ("es geht mir besser","I feel better","","phrase","Es geht mir schon besser.")],
    [("Ich habe Kopfschmerzen / Fieber.","I have a headache / fever."),("Mir tut … weh.","My … hurts."),("Du solltest zum Arzt gehen.","You should go to the doctor."),("Gehen Sie zum Arzt!","Go to the doctor!"),("Es geht mir besser / schlechter.","I feel better / worse.")],
    "Describe an illness (symptoms) and the advice a friend/doctor gave you.",
    "Ich habe Kopfschmerzen und Halsschmerzen, und ich glaube, ich habe Fieber. Meine Freundin sagt: Du solltest nach Hause gehen, viel Tee trinken und dich ausruhen. Morgen gehe ich zum Arzt.")

# ---------------- TAG 23 ----------------
day(23, "Pläne fürs Wochenende", "Was machst du am Wochenende?", "Zukünftige Pläne mit Präsens und wollen ausdrücken.",
    "wollen (will, willst, will); Zukunft mit Präsens + Zeitadverb; am Wochenende",
    "German often uses present tense for future plans with a time word: <b>Morgen gehe ich ins Kino.</b> <b>wollen</b> (want to): ich will, du willst, er will, wir wollen. Ask plans: <b>Was hast du am Wochenende vor?</b> (vorhaben).",
    ["Am Wochenende will ich schlafen.","Nächste Woche fahre ich nach Hamburg.","Was hast du vor?","Wir wollen eine Party machen."],
    [("Jonas","Was hast du am Wochenende vor, Mia?","What are your plans for the weekend, Mia?"),
     ("Mia","Ich will am Samstag schlafen! Die Woche war anstrengend.","I want to sleep on Saturday! The week was exhausting."),
     ("Jonas","Verständlich. Am Sonntag wollen wir eine Grillparty im Park machen. Kommst du?","Understandable. On Sunday we want to have a barbecue party in the park. Are you coming?"),
     ("Mia","Eine Grillparty? Ich bin dabei! Was soll ich mitbringen?","A barbecue party? I'm in! What should I bring?"),
     ("Jonas","Bring Salat oder Getränke mit. Wir haben schon Fleisch und Brot.","Bring salad or drinks. We already have meat and bread."),
     ("Mia","Ich bringe einen spanischen Salat und Wein mit. Wann geht es los?","I'll bring a Spanish salad and wine. When does it start?"),
     ("Jonas","Um drei Uhr nachmittags, im Tiergarten. Ich schicke dir die Adresse.","At three in the afternoon, in the Tiergarten. I'll send you the address."),
     ("Mia","Perfekt! Ich freue mich schon.","Perfect! I'm already looking forward to it.")],
    [("der Plan","the plan","der","noun","Was ist dein Plan?"),
     ("vorhaben","to plan/intend","","verb","Was hast du vor?"),
     ("wollen","to want to","","verb","Ich will schlafen."),
     ("am Wochenende","at the weekend","","phrase","Am Wochenende habe ich frei."),
     ("morgen / nächste Woche","tomorrow / next week","","adv","Morgen gehe ich schwimmen."),
     ("die Party","the party","die","noun","Wir machen eine Party."),
     ("mitbringen","to bring along","","verb","Was soll ich mitbringen?"),
     ("das Getränk","the drink","das","noun","Bring Getränke mit!"),
     ("der Salat","the salad","der","noun","Ich mache einen Salat."),
     ("sich freuen auf","to look forward to","","verb","Ich freue mich auf die Party."),
     ("anstrengend","exhausting","","adj","Die Arbeit ist anstrengend."),
     ("die Adresse","the address","die","noun","Wie ist die Adresse?"),
     ("losgehen","to start","","verb","Wann geht es los?"),
     ("dabei sein","to be in/joining","","phrase","Ich bin dabei!")],
    [("Was hast du am Wochenende vor?","What are your weekend plans?"),("Ich will …","I want to …"),("Kommst du? — Ich bin dabei!","Are you coming? — I'm in!"),("Was soll ich mitbringen?","What should I bring?"),("Ich freue mich schon.","I'm already looking forward to it.")],
    "Describe your weekend plans in detail (days, times, who with).",
    "Am Samstag will ich schlafen und dann einkaufen. Am Sonntag gehe ich um 15 Uhr zu einer Grillparty im Park. Ich bringe Salat und Wein mit. Ich freue mich schon!")

# ---------------- TAG 24 ----------------
day(24, "Einladung & Party", "Du bist eingeladen!", "Eine Einladung annehmen/ablehnen und auf einer Party reden.",
    "einladen (lädt ein); mitkommen; dürfen; Präpositionen bei jemandem",
    "<b>einladen</b> (invite): ich lade dich ein. Accept: <b>Ja, gerne! Ich komme.</b> Decline politely: <b>Danke für die Einladung, aber ich kann leider nicht.</b> At a party: small talk with was, wer, woher, was machst du beruflich.",
    ["Ich lade dich zu meiner Party ein.","Darf ich einen Freund mitbringen?","Danke für die Einladung!","Leider kann ich nicht, ich habe keine Zeit."],
    [("Mia","Hallo Jonas! Ich lade dich nächste Woche zu meiner Geburtstagsparty ein.","Hi Jonas! I invite you to my birthday party next week."),
     ("Jonas","Oh, vielen Dank! Wann ist die Party?","Oh, thank you very much! When is the party?"),
     ("Mia","Am Freitag ab 20 Uhr, bei mir zu Hause. Darfst du etwas mitbringen?","On Friday from 8pm, at my place. You may bring something?"),
     ("Jonas","Klar! Darf ich einen Freund mitbringen?","Sure! May I bring a friend?"),
     ("Mia","Natürlich! Jeder ist willkommen. Bring einfach Musik mit.","Of course! Everyone is welcome. Just bring music."),
     ("Jonas","Super. Ach, ich muss dich leider an etwas erinnern: Du musst noch die Musik vorbereiten.","Great. Oh, I unfortunately have to remind you of something: you still have to prepare the music."),
     ("Mia","Stimmt! Danke für den Hinweis. Ich mache das heute Abend.","Right! Thanks for the hint. I'll do that this evening."),
     ("Jonas","Bis Freitag! Ich freue mich.","See you Friday! I'm looking forward to it.")],
    [("die Einladung","the invitation","die","noun","Danke für die Einladung!"),
     ("einladen","to invite","","verb","Ich lade dich ein."),
     ("annehmen / ablehnen","to accept / decline","","verb","Ich nehme die Einladung an."),
     ("der Geburtstag","the birthday","der","noun","Heute ist mein Geburtstag."),
     ("die Party","the party","die","noun","Die Party ist toll."),
     ("mitbringen","to bring along","","verb","Was bringst du mit?"),
     ("dürfen","may / to be allowed","","verb","Darf ich hereinkommen?"),
     ("natürlich","of course","","adv","Natürlich kannst du kommen."),
     ("jeder / jede / jedes","everyone / each","","pron","Jeder ist willkommen."),
     ("willkommen","welcome","","adj","Willkommen bei mir!"),
     ("sich erinnern an","to remember","","verb","Ich erinnere mich an dich."),
     ("der Hinweis","the hint","der","noun","Danke für den Hinweis!"),
     ("vorbereiten","to prepare","","verb","Ich bereite das Essen vor."),
     ("vielen Dank","thank you very much","","phrase","Vielen Dank für die Einladung!")],
    [("Ich lade dich zu … ein.","I invite you to …"),("Danke für die Einladung!","Thanks for the invitation!"),("Darf ich … mitbringen?","May I bring …?"),("Leider kann ich nicht.","Unfortunately I can't."),("Jeder ist willkommen.","Everyone is welcome.")],
    "Invite someone to an event, they ask to bring a friend, you agree, remind them of one detail.",
    "Ich lade dich zu meiner Geburtstagsparty ein: am Freitag ab 20 Uhr, bei mir zu Hause. — Darf ich einen Freund mitbringen? — Natürlich! Jeder ist willkommen. Bring einfach Getränke mit.")

# ---------------- TAG 25 ----------------
day(25, "Auf dem Markt", "Einkaufen auf dem Wochenmarkt", "Auf dem Markt einkaufen, Preise verhandeln, Zahlen bis 100.",
    "Zahlen 20–100; wie viel / wie viele; viel/viele; etwas/nichts",
    "Numbers 21–99: units first, then tens, with <b>und</b>: <b>vierundzwanzig</b> (24), <b>siebenundfünfzig</b> (57). <b>viel</b> (much, uncountable) vs <b>viele</b> (many, plural). <b>etwas</b>=some, <b>nichts</b>=nothing.",
    ["Das kostet fünfunddreißig Euro.","Ich habe noch etwas Geld.","Wie viele Äpfel möchtest du?","Ich nehme ein Kilo Tomaten."],
    [("Marktfrau","Guten Morgen! Frische Erdbeeren! Nur drei Euro das Kilo!","Good morning! Fresh strawberries! Only three euros a kilo!"),
     ("Mia","Die sehen gut aus! Wie viel kostet ein Kilo?","They look good! How much is a kilo?"),
     ("Marktfrau","Drei Euro, oder zwei Kilo für fünf Euro.","Three euros, or two kilos for five euros."),
     ("Mia","Gut, ich nehme zwei Kilo. Haben Sie auch frisches Gemüse?","Good, I'll take two kilos. Do you also have fresh vegetables?"),
     ("Marktfrau","Natürlich! Tomaten, Gurken, Paprika — alles frisch vom Feld.","Of course! Tomatoes, cucumbers, peppers — all fresh from the field."),
     ("Mia","Ich nehme vier Tomaten und eine Gurke. Wie viel macht das zusammen?","I'll take four tomatoes and one cucumber. How much is that together?"),
     ("Marktfrau","Das macht zusammen sieben Euro fünfzig. Möchten Sie noch etwas?","That's seven euros fifty together. Would you like anything else?"),
     ("Mia","Nein danke, das ist alles. Hier sind zehn Euro.","No thanks, that's all. Here's ten euros."),
     ("Marktfrau","Danke schön, und zwei fünfzig Rückgeld. Schönen Tag noch!","Thank you, and two fifty change. Have a nice day!")],
    [("der Markt","the market","der","noun","Ich gehe auf den Markt."),
     ("frisch","fresh","","adj","Das Obst ist frisch."),
     ("die Erdbeere","the strawberry","die","noun","Erdbeeren sind süß."),
     ("das Gemüse","the vegetables","das","noun","Gemüse ist gesund."),
     ("die Tomate","the tomato","die","noun","Ich nehme vier Tomaten."),
     ("die Gurke","the cucumber","die","noun","Eine Gurke, bitte."),
     ("das Kilo","the kilo","das","noun","Ein Kilo Äpfel, bitte."),
     ("viel / viele","much / many","","adj","Ich habe viel Geld / viele Äpfel."),
     ("etwas","something / some","","pron","Ich möchte etwas Wasser."),
     ("nichts","nothing","","pron","Ich möchte nichts."),
     ("zusammen","together / total","","adv","Was macht das zusammen?"),
     ("das Rückgeld","the change","das","noun","Hier ist Ihr Rückgeld."),
     ("kosten","to cost","","verb","Was kostet das?"),
     ("schönen Tag noch!","have a nice day!","","phrase","Schönen Tag noch!")],
    [("Wie viel kostet …?","How much does … cost?"),("Ich nehme …","I'll take …"),("Möchten Sie noch etwas?","Would you like anything else?"),("Das ist alles.","That's all."),("Schönen Tag noch!","Have a nice day!")],
    "Role-play a market purchase: ask price, take items, pay, get change.",
    "Wie viel kostet ein Kilo Erdbeeren? — Drei Euro. Ich nehme zwei Kilo und vier Tomaten. Das macht zusammen sieben Euro fünfzig. Hier sind zehn Euro — danke für das Rückgeld!")

# ---------------- TAG 26 ----------------
day(26, "Post & Bank", "Auf die Post und zur Bank", "Ein Paket schicken und Geld abheben.",
    "schicken/senden; wie viel kostet das Porto?; Geld; Dativ fest: geben (ich gebe dir…)",
    "At the post office: <b>Ich möchte ein Paket nach … schicken.</b> <b>Wie viel kostet das Porto?</b> At the bank: <b>Ich möchte Geld abheben/einzahlen.</b> <b>geben</b> is irregular and takes dative + accusative: <b>Ich gebe dir das Geld.</b> (learn as chunk).",
    ["Ich möchte ein Paket nach Spanien schicken.","Wie viel kostet das Porto?","Ich möchte 100 Euro abheben.","Können Sie mir das geben?"] ,
    [("Mia","Guten Tag! Ich möchte ein Paket nach Madrid schicken. Wie viel kostet das Porto?","Hello! I'd like to send a package to Madrid. How much is the postage?"),
     ("Postangestellte","Das Paket wiegt zwei Kilo. Das Porto kostet vierzehn Euro.","The package weighs two kilos. Postage costs fourteen euros."),
     ("Mia","Okay. Und ich möchte noch zwei Briefmarken für einen Brief nach Berlin.","Okay. And I'd also like two stamps for a letter to Berlin."),
     ("Postangestellte","Zwei Briefmarken kosten zusammen ein Euro sechzig. Zusammen mit dem Paket: fünfzehn Euro sechzig.","Two stamps cost one euro sixty together. With the package: fifteen euros sixty."),
     ("Mia","Hier ist zwanzig Euro. — Später, an der Bank: Guten Tag, ich möchte hundert Euro abheben.","Here's twenty euros. — Later, at the bank: Hello, I'd like to withdraw one hundred euros."),
     ("Bankangestellter","Bitte stecken Sie Ihre Karte in den Automaten und geben Sie Ihre PIN ein.","Please insert your card into the machine and enter your PIN."),
     ("Mia","Danke. Kann ich auch 50-Euro-Scheine bekommen?","Thanks. Can I also get 50-euro notes?"),
     ("Bankangestellter","Natürlich. Hier sind Ihre hundert Euro.","Of course. Here are your one hundred euros.")],
    [("die Post","the post office","die","noun","Ich gehe zur Post."),
     ("die Bank","the bank","die","noun","Die Bank ist um die Ecke."),
     ("das Paket","the package","das","noun","Ich schicke ein Paket."),
     ("schicken / senden","to send","","verb","Ich schicke ein Paket."),
     ("das Porto","the postage","das","noun","Wie viel kostet das Porto?"),
     ("die Briefmarke","the stamp","die","noun","Ich brauche Briefmarken."),
     ("der Brief","the letter","der","noun","Ich schreibe einen Brief."),
     ("Geld abheben","to withdraw money","","phrase","Ich hebe Geld ab."),
     ("die Karte","the card","die","noun","Stecken Sie die Karte ein."),
     ("die PIN","the PIN","die","noun","Geben Sie Ihre PIN ein."),
     ("der Euro-Schein","the euro note","der","noun","Ein 50-Euro-Schein."),
     ("wiegen","to weigh","","verb","Das Paket wiegt 2 Kilo."),
     ("geben","to give","","verb","Ich gebe dir das Geld."),
     ("bekommen","to get/receive","","verb","Ich bekomme Geld.")],
    [("Ich möchte ein Paket nach … schicken.","I'd like to send a package to …"),("Wie viel kostet das Porto?","How much is the postage?"),("Ich möchte … Euro abheben.","I'd like to withdraw … euros."),("Geben Sie Ihre PIN ein.","Enter your PIN."),("Hier ist Ihr Rückgeld.","Here's your change.")],
    "Describe going to the post office and the bank: what you sent/withdrew and how much it cost.",
    "Auf der Post schicke ich ein Paket nach Madrid. Das Porto kostet 14 Euro. Dann gehe ich zur Bank und hebe 100 Euro ab. Ich bekomme zwei 50-Euro-Scheine.")

# ---------------- TAG 27 ----------------
day(27, "Handy & Nachrichten", "Ruf mich an!","Über das Handy sprechen und Nachrichten schicken.",
    "anrufen; zurückrufen; Nachricht schicken; erreichbar sein; trennbare Verben wiederholen",
    "Phone verbs: <b>anrufen</b> (call), <b>zurückrufen</b> (call back), <b>auflegen</b> (hang up), <b>abnehmen</b> (pick up). <b>Erreichbar sein</b>=be reachable. Messages: <b>Ich schicke dir eine SMS/WhatsApp-Nachricht.</b> Review separable verbs (prefix at end).",
    ["Ich rufe dich später an.","Ruf mich zurück!","Ich bin nicht erreichbar.","Schick mir eine Nachricht!"] ,
    [("Mia","(am Telefon) Hallo Jonas! Ich bin's, Mia. Warum rufst du nicht an?","(on phone) Hi Jonas! It's me, Mia. Why don't you call?"),
     ("Jonas","Oh, sorry! Mein Akku ist leer. Ich konnte dich nicht anrufen.","Oh, sorry! My battery is empty. I couldn't call you."),
     ("Mia","Kein Problem. Hast du meine Nachricht gesehen? Ich schreibe dir per WhatsApp.","No problem. Did you see my message? I write you via WhatsApp."),
     ("Jonas","Ja, gesehen. Ich antworte dir später, ich bin gerade in der U-Bahn.","Yes, seen. I'll answer you later, I'm just in the subway."),
     ("Mia","Okay, in der U-Bahn ist kein Empfang. Ruf mich zurück, wenn du wieder Empfang hast.","Okay, in the subway there's no reception. Call me back when you have reception again."),
     ("Jonas","Mache ich. Wenn ich nicht rangehe, schick mir eine Sprachnachricht.","Will do. If I don't pick up, send me a voice message."),
     ("Mia","Gut. Bis später! Ich lege auf.","Good. See you later! I'll hang up."),
     ("Jonas","Tschüss!","Bye!")],
    [("das Handy","the mobile phone","das","noun","Mein Handy ist neu."),
     ("anrufen","to call","","verb","Ich rufe dich an."),
     ("zurückrufen","to call back","","verb","Ruf mich zurück!"),
     ("auflegen","to hang up","","verb","Ich lege auf."),
     ("rangehen","to pick up (phone)","","verb","Er geht nicht ran."),
     ("die Nachricht","the message","die","noun","Schick mir eine Nachricht!"),
     ("die Sprachnachricht","voice message","die","noun","Ich schicke eine Sprachnachricht."),
     ("der Akku","the battery","der","noun","Mein Akku ist leer."),
     ("leer / voll","empty / full","","adj","Der Akku ist leer."),
     ("der Empfang","the reception","der","noun","Kein Empfang im Keller."),
     ("erreichbar","reachable","","adj","Ich bin heute erreichbar."),
     ("antworten","to answer","","verb","Ich antworte dir später."),
     ("sehen","to see","","verb","Ich habe die Nachricht gesehen."),
     ("später","later","","adv","Bis später!")],
    [("Ruf mich an / zurück!","Call me / call me back!"),("Ich bin (nicht) erreichbar.","I am (not) reachable."),("Schick mir eine Nachricht.","Send me a message."),("Mein Akku ist leer.","My battery is empty."),("Ich lege auf.","I'm hanging up.")],
    "Describe a phone call: why someone didn't answer, what you agreed, how you'll stay in touch.",
    "Jonas ruft mich nicht an, weil sein Akku leer ist. Ich schicke ihm eine Nachricht. Er ruft mich später zurück. Wenn er nicht rangeht, schicke ich eine Sprachnachricht.")

# ---------------- TAG 28 ----------------
day(28, "Berlin entdecken", "Sehenswürdigkeiten in Berlin", "Über Sehenswürdigkeiten reden und eine Stadttour planen.",
    "besichtigen; besuchen; Modalverben wiederholen; Adjektive beschreiben",
    "Sightseeing: <b>besichtigen</b> (visit a place/building), <b>besuchen</b> (visit a person/event). Describe with adjectives: <b>groß, alt, modern, beeindruckend, schön.</b> Plan a tour with zuerst, dann, danach, am Ende.",
    ["Wir besichtigen das Brandenburger Tor.","Das Museum ist sehr interessant.","Zuerst gehen wir zum Reichstag, dann zum Holocaust-Mahnmal.","Berlin ist groß und lebendig."],
    [("Jonas","Heute mache ich eine Stadttour mit dir. Was willst du in Berlin unbedingt sehen?","Today I'll do a city tour with you. What do you absolutely want to see in Berlin?"),
     ("Mia","Das Brandenburger Tor! Und den Reichstag. Ist der Eintritt frei?","The Brandenburg Gate! And the Reichstag. Is entry free?"),
     ("Jonas","Ja, aber für die Reichstagskuppel muss man sich vorher anmelden. Danach gehen wir zum Holocaust-Mahnmal.","Yes, but for the Reichstag dome you have to register beforehand. After that we go to the Holocaust Memorial."),
     ("Mia","Das soll sehr beeindruckend sein. Und dann?","That's supposed to be very impressive. And then?"),
     ("Jonas","Dann spazieren wir durch den Tiergarten und trinken einen Kaffee am Kudamm.","Then we stroll through the Tiergarten and drink a coffee on the Kurfürstendamm."),
     ("Mia","Klingt perfekt! Berlin ist so groß und lebendig. Ich liebe diese Stadt.","Sounds perfect! Berlin is so big and lively. I love this city."),
     ("Jonas","Am Ende gehen wir zum East Side Gallery — die längste Open-Air-Galerie der Welt.","At the end we go to the East Side Gallery — the longest open-air gallery in the world."),
     ("Mia","Wow! Ich mache viele Fotos. Zeig mir dein Berlin!","Wow! I'll take lots of photos. Show me your Berlin!")],
    [("die Sehenswürdigkeit","sight/landmark","die","noun","Berlin hat viele Sehenswürdigkeiten."),
     ("besichtigen","to visit (sight)","","verb","Wir besichtigen das Museum."),
     ("besuchen","to visit (person/event)","","verb","Ich besuche meine Schwester."),
     ("der Eintritt","the entry/admission","der","noun","Der Eintritt ist frei."),
     ("frei","free","","adj","Der Eintritt ist frei."),
     ("beeindruckend","impressive","","adj","Das Tor ist beeindruckend."),
     ("spazieren gehen","to go for a stroll","","phrase","Wir spazieren durch den Park."),
     ("die Stadt","the city","die","noun","Berlin ist eine große Stadt."),
     ("groß / klein","big / small","","adj","Berlin ist groß."),
     ("modern / alt","modern / old","","adj","Das Gebäude ist modern."),
     ("zuerst / dann / danach","first / then / after that","","adv","Zuerst… dann… danach…"),
     ("am Ende","in the end","","phrase","Am Ende trinken wir Kaffee."),
     ("das Foto","the photo","das","noun","Ich mache viele Fotos."),
     ("die Galerie","the gallery","die","noun","Die East Side Gallery ist berühmt.")],
    [("Was willst du unbedingt sehen?","What do you absolutely want to see?"),("Ist der Eintritt frei?","Is entry free?"),("Zuerst …, dann …, danach …","First …, then …, after that …"),("Das ist sehr beeindruckend.","That's very impressive."),("Ich liebe diese Stadt!","I love this city!")],
    "Plan a city tour: 3 sights in order, say one adjective about each, end with a coffee.",
    "Zuerst besichtigen wir das Brandenburger Tor — es ist beeindruckend. Dann gehen wir zum Reichstag, er ist groß und modern. Danach spazieren wir durch den Tiergarten. Am Ende trinken wir einen Kaffee.")

# ---------------- TAG 29 ----------------
day(29, "Wiederholung", "Wochenrückblick", "Alles aus A1.1 wiederholen und Lücken finden.",
    "Wiederholung: Präsens, Akkusativ, trennbare Verben, Modalverben, Negation, Präpositionen",
    "Review day! Today's session interleaves everything from days 1–28: present tense (regular + irregular), accusative articles, separable verbs, modal verbs (möchten, müssen, wollen, sollen, dürfen), kein/nicht, prepositions of place/time. Use retrieval — no peeking!",
    ["Ich rufe dich morgen an.","Er möchte ein Wasser.","Wir haben keine Zeit.","Die Präsentation ist fertig."],
    [("Mia","(Tagebuch) Heute ist mein 29. Tag in Berlin. Ich kann mich vorstellen, einkaufen, im Restaurant bestellen und zum Arzt gehen.","(Diary) Today is my 29th day in Berlin. I can introduce myself, shop, order in restaurants and go to the doctor."),
     ("Jonas","Dein Deutsch ist schon viel besser! Du sprichst fast fließend.","Your German is already much better! You speak almost fluently."),
     ("Mia","Danke! Aber ich mache noch viele Fehler mit den Artikeln und der Wortstellung.","Thanks! But I still make many mistakes with articles and word order."),
     ("Jonas","Das ist normal. Übung macht den Meister. Morgen ist dein letzter Tag von A1.1.","That's normal. Practice makes perfect. Tomorrow is your last day of A1.1."),
     ("Mia","Schon? Dann mache ich morgen eine große Selbstvorstellung — auf Deutsch!","Already? Then tomorrow I'll do a big self-introduction — in German!"),
     ("Jonas","Super! Ich bin dein Publikum. Erzähl alles: Herkunft, Familie, Arbeit, Hobbys, Wohnung, Berlin.","Great! I'll be your audience. Tell everything: origin, family, work, hobbies, apartment, Berlin."),
     ("Mia","Abgemacht! Ich übe heute Abend noch mal alle Vokabeln.","Deal! I'll review all the vocabulary again this evening.")],
    [("wiederholen","to repeat/review","","verb","Ich wiederhole die Grammatik."),
     ("die Wiederholung","the review","die","noun","Heute ist Wiederholung."),
     ("der Fehler","the mistake","der","noun","Ich mache viele Fehler."),
     ("besser","better","","adj","Dein Deutsch ist besser."),
     ("fließend","fluent","","adj","Ich spreche fließend Spanisch."),
     ("normal","normal","","adj","Das ist normal."),
     ("die Grammatik","the grammar","die","noun","Die Grammatik ist schwierig."),
     ("der Artikel","the article (der/die/das)","der","noun","Ich vergesse die Artikel."),
     ("die Wortstellung","the word order","die","noun","Die Wortstellung ist schwierig."),
     ("üben","to practice","","verb","Ich übe jeden Tag."),
     ("die Vokabeln","the vocabulary","die","noun","Ich lerne Vokabeln."),
     ("sich vorstellen","to introduce oneself","","verb","Ich stelle mich vor."),
     ("erzählen","to tell/narrate","","verb","Erzähl mir von deiner Reise."),
     ("abgemacht!","it's a deal!","","phrase","Abgemacht! Bis morgen!")],
    [("Ich kann schon …","I can already …"),("Ich mache noch Fehler mit …","I still make mistakes with …"),("Das ist normal.","That's normal."),("Übung macht den Meister.","Practice makes perfect."),("Abgemacht!","It's a deal!")],
    "Write/say a short review: what you can now do in German, and what is still difficult.",
    "Nach 29 Tagen kann ich mich vorstellen, einkaufen und im Restaurant bestellen. Ich kann über Familie, Hobbys und Arbeit sprechen. Noch schwierig sind die Artikel und die Wortstellung. Aber Übung macht den Meister!")

# ---------------- TAG 30 ----------------
day(30, "A1.1 Abschlussprojekt", "Mein Leben in Berlin", "Eine komplette Selbstvorstellung halten — A1.1 Abschluss.",
    "Abschluss: alle Strukturen kombiniert; Selbstvorstellung; Ausblick auf A1.2",
    "Final project day! Combine everything: greeting, name, origin, family, job/studies, apartment, hobbies, likes/dislikes, daily routine, weekend plans, your opinion of Berlin. Speak for 60–90 seconds. Then compare with the model. Nächster Halt: A1.2!",
    ["Ich heiße Mia und komme aus Madrid.","Ich wohne seit einem Monat in Berlin.","Ich arbeite als Designerin in einem Büro.","Am Wochenende treffe ich mich mit Freunden."],
    [("Mia","(vor Jonas und Leila) Hallo! Ich heiße Mia López. Ich komme aus Madrid und bin seit einem Monat in Berlin.","(in front of Jonas and Leila) Hi! I'm Mia López. I come from Madrid and have been in Berlin for a month."),
     ("Mia","Ich bin Designerin und mache ein Praktikum in einem kleinen Büro in Kreuzberg. Meine Kollegin Leila ist hier — hallo!","I'm a designer and do an internship in a small office in Kreuzberg. My colleague Leila is here — hi!"),
     ("Mia","Ich wohne in einer kleinen Wohnung mit einem Balkon. Ich habe einen Bruder und eine Schwester in Spanien.","I live in a small apartment with a balcony. I have a brother and a sister in Spain."),
     ("Mia","In meiner Freizeit lese ich gern, fotografiere und koche. Am Wochenende treffe ich mich mit Freunden im Park.","In my free time I like reading, photographing and cooking. At the weekend I meet friends in the park."),
     ("Mia","Ich mag Berlin sehr: die Stadt ist lebendig und die Menschen sind offen. Nur das Wetter — manchmal regnet es zu viel!","I like Berlin a lot: the city is lively and the people are open. Only the weather — sometimes it rains too much!"),
     ("Jonas","(applaudiert) Toll! Das war perfekt! Du bist bereit für A1.2.","(applauds) Great! That was perfect! You're ready for A1.2."),
     ("Leila","Weiter so! Nächstes Thema: Perfekt und Vergangenheit — dann kannst du von deiner Reise erzählen!","Keep it up! Next topic: perfect tense and past — then you can tell about your trip!"),
     ("Mia","Danke! Ich freue mich auf A1.2. Auf Wiedersehen, A1.1!","Thanks! I'm looking forward to A1.2. Goodbye, A1.1!")],
    [("die Selbstvorstellung","self-introduction","die","noun","Ich halte eine Selbstvorstellung."),
     ("seit","since (time)","","prep","Ich bin seit einem Monat hier."),
     ("der Monat","the month","der","noun","in einem Monat"),
     ("bereit","ready","","adj","Ich bin bereit für A1.2."),
     ("der Abschluss","the completion/graduation","der","noun","Heute ist der Abschluss von A1.1."),
     ("das Projekt","the project","das","noun","Das Abschlussprojekt."),
     ("erzählen","to tell/narrate","","verb","Erzähl uns von Berlin!"),
     ("die Meinung","the opinion","die","noun","Was ist deine Meinung?"),
     ("mögen","to like","","verb","Ich mag Berlin."),
     ("lebendig","lively","","adj","Berlin ist lebendig."),
     ("offen","open","","adj","Die Menschen sind offen."),
     ("nächste Woche / nächstes Level","next week / next level","","phrase","Nächstes Level: A1.2."),
     ("sich freuen auf","to look forward to","","verb","Ich freue mich auf A1.2."),
     ("weiter so!","keep it up!","","phrase","Weiter so, du schaffst das!")],
    [("Ich heiße … und komme aus …","I'm … and come from …"),("Ich bin seit … in …","I've been in … for …"),("Ich arbeite als …","I work as a …"),("Ich mag … sehr.","I like … a lot."),("Ich bin bereit für …","I'm ready for …")],
    "FINAL TASK: Give a 60–90 second self-introduction in German covering: name, origin, family, job/studies, apartment, hobbies, daily routine, weekend plans, and your opinion of Berlin. Record yourself!",
    "Hallo! Ich heiße Mia López. Ich komme aus Madrid und bin seit einem Monat in Berlin. Ich bin Designerin und mache ein Praktikum in Kreuzberg. Ich wohne in einer kleinen Wohnung mit Balkon. Ich habe einen Bruder und eine Schwester. In meiner Freizeit lese und koche ich gern. Am Wochenende treffe ich mich mit Freunden. Ich mag Berlin sehr — es ist lebendig. Ich bin bereit für A1.2!")

# ---------------- write JS ----------------
out = "/* Deutsch Jetzt! — lesson data (A1.1, Tage 1–30). Original content. Auto-generated. */\n"
out += "/* To extend: append more day objects following the same schema (see docs/DESIGN.md). */\n"
out += "window.LESSONS = " + json.dumps(D, ensure_ascii=False, indent=1) + ";\n"
with open('/home/user/.super_doubao/super-doubao-runtime/workspace/deutsch-jetzt/data/lessons.js', 'w', encoding='utf-8') as f:
    f.write(out)
print(f"Wrote {len(D)} days, {sum(len(d['vocab']) for d in D)} vocab items, {sum(len(d['episode']) for d in D)} episode lines.")
